//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiationHeader",
    "mandatedAction",
    "uniqueRequestId",
    "requestedActionType",
    "uniqueUserId",
    "uniqueItemId",
    "dateForReturnOrIndeterminateLoanPeriodFlagOrNonReturnableFlag",
    "renewalNotPermitted",
    "fiscalTransactionInformation",
    "itemOptionalFields",
    "userOptionalFields"
})
@XmlRootElement(name = "AcceptItem")
public class AcceptItem {

    @XmlElement(name = "InitiationHeader", required = true)
    protected InitiationHeader initiationHeader;
    @XmlElement(name = "MandatedAction")
    protected MandatedAction mandatedAction;
    @XmlElement(name = "UniqueRequestId", required = true)
    protected UniqueRequestId uniqueRequestId;
    @XmlElement(name = "RequestedActionType", required = true)
    protected RequestedActionType requestedActionType;
    @XmlElement(name = "UniqueUserId")
    protected UniqueUserId uniqueUserId;
    @XmlElement(name = "UniqueItemId")
    protected UniqueItemId uniqueItemId;
    @XmlElements({
        @XmlElement(name = "DateForReturn", type = DateForReturn.class),
        @XmlElement(name = "IndeterminateLoanPeriodFlag", type = IndeterminateLoanPeriodFlag.class),
        @XmlElement(name = "NonReturnableFlag", type = NonReturnableFlag.class)
    })
    protected List<Object> dateForReturnOrIndeterminateLoanPeriodFlagOrNonReturnableFlag;
    @XmlElement(name = "RenewalNotPermitted")
    protected RenewalNotPermitted renewalNotPermitted;
    @XmlElement(name = "FiscalTransactionInformation")
    protected FiscalTransactionInformation fiscalTransactionInformation;
    @XmlElement(name = "ItemOptionalFields")
    protected ItemOptionalFields itemOptionalFields;
    @XmlElement(name = "UserOptionalFields")
    protected UserOptionalFields userOptionalFields;

    /**
     * Gets the value of the initiationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InitiationHeader }
     *     
     */
    public InitiationHeader getInitiationHeader() {
        return initiationHeader;
    }

    /**
     * Sets the value of the initiationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiationHeader }
     *     
     */
    public void setInitiationHeader(InitiationHeader value) {
        this.initiationHeader = value;
    }

    /**
     * Gets the value of the mandatedAction property.
     * 
     * @return
     *     possible object is
     *     {@link MandatedAction }
     *     
     */
    public MandatedAction getMandatedAction() {
        return mandatedAction;
    }

    /**
     * Sets the value of the mandatedAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandatedAction }
     *     
     */
    public void setMandatedAction(MandatedAction value) {
        this.mandatedAction = value;
    }

    /**
     * Gets the value of the uniqueRequestId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueRequestId }
     *     
     */
    public UniqueRequestId getUniqueRequestId() {
        return uniqueRequestId;
    }

    /**
     * Sets the value of the uniqueRequestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueRequestId }
     *     
     */
    public void setUniqueRequestId(UniqueRequestId value) {
        this.uniqueRequestId = value;
    }

    /**
     * Gets the value of the requestedActionType property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedActionType }
     *     
     */
    public RequestedActionType getRequestedActionType() {
        return requestedActionType;
    }

    /**
     * Sets the value of the requestedActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedActionType }
     *     
     */
    public void setRequestedActionType(RequestedActionType value) {
        this.requestedActionType = value;
    }

    /**
     * Gets the value of the uniqueUserId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueUserId }
     *     
     */
    public UniqueUserId getUniqueUserId() {
        return uniqueUserId;
    }

    /**
     * Sets the value of the uniqueUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueUserId }
     *     
     */
    public void setUniqueUserId(UniqueUserId value) {
        this.uniqueUserId = value;
    }

    /**
     * Gets the value of the uniqueItemId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueItemId }
     *     
     */
    public UniqueItemId getUniqueItemId() {
        return uniqueItemId;
    }

    /**
     * Sets the value of the uniqueItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueItemId }
     *     
     */
    public void setUniqueItemId(UniqueItemId value) {
        this.uniqueItemId = value;
    }

    /**
     * Gets the value of the dateForReturnOrIndeterminateLoanPeriodFlagOrNonReturnableFlag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateForReturnOrIndeterminateLoanPeriodFlagOrNonReturnableFlag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateForReturnOrIndeterminateLoanPeriodFlagOrNonReturnableFlag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateForReturn }
     * {@link IndeterminateLoanPeriodFlag }
     * {@link NonReturnableFlag }
     * 
     * 
     */
    public List<Object> getDateForReturnOrIndeterminateLoanPeriodFlagOrNonReturnableFlag() {
        if (dateForReturnOrIndeterminateLoanPeriodFlagOrNonReturnableFlag == null) {
            dateForReturnOrIndeterminateLoanPeriodFlagOrNonReturnableFlag = new ArrayList<Object>();
        }
        return this.dateForReturnOrIndeterminateLoanPeriodFlagOrNonReturnableFlag;
    }

    /**
     * Gets the value of the renewalNotPermitted property.
     * 
     * @return
     *     possible object is
     *     {@link RenewalNotPermitted }
     *     
     */
    public RenewalNotPermitted getRenewalNotPermitted() {
        return renewalNotPermitted;
    }

    /**
     * Sets the value of the renewalNotPermitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenewalNotPermitted }
     *     
     */
    public void setRenewalNotPermitted(RenewalNotPermitted value) {
        this.renewalNotPermitted = value;
    }

    /**
     * Gets the value of the fiscalTransactionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link FiscalTransactionInformation }
     *     
     */
    public FiscalTransactionInformation getFiscalTransactionInformation() {
        return fiscalTransactionInformation;
    }

    /**
     * Sets the value of the fiscalTransactionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiscalTransactionInformation }
     *     
     */
    public void setFiscalTransactionInformation(FiscalTransactionInformation value) {
        this.fiscalTransactionInformation = value;
    }

    /**
     * Gets the value of the itemOptionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link ItemOptionalFields }
     *     
     */
    public ItemOptionalFields getItemOptionalFields() {
        return itemOptionalFields;
    }

    /**
     * Sets the value of the itemOptionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemOptionalFields }
     *     
     */
    public void setItemOptionalFields(ItemOptionalFields value) {
        this.itemOptionalFields = value;
    }

    /**
     * Gets the value of the userOptionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link UserOptionalFields }
     *     
     */
    public UserOptionalFields getUserOptionalFields() {
        return userOptionalFields;
    }

    /**
     * Sets the value of the userOptionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserOptionalFields }
     *     
     */
    public void setUserOptionalFields(UserOptionalFields value) {
        this.userOptionalFields = value;
    }

}
