//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiationHeader",
    "uniqueAgencyId",
    "deleteAgencyFields",
    "addAgencyFields"
})
@XmlRootElement(name = "AgencyUpdated")
public class AgencyUpdated {

    @XmlElement(name = "InitiationHeader", required = true)
    protected InitiationHeader initiationHeader;
    @XmlElement(name = "UniqueAgencyId", required = true)
    protected UniqueAgencyId uniqueAgencyId;
    @XmlElement(name = "DeleteAgencyFields")
    protected DeleteAgencyFields deleteAgencyFields;
    @XmlElement(name = "AddAgencyFields")
    protected AddAgencyFields addAgencyFields;

    /**
     * Gets the value of the initiationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InitiationHeader }
     *     
     */
    public InitiationHeader getInitiationHeader() {
        return initiationHeader;
    }

    /**
     * Sets the value of the initiationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiationHeader }
     *     
     */
    public void setInitiationHeader(InitiationHeader value) {
        this.initiationHeader = value;
    }

    /**
     * Gets the value of the uniqueAgencyId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueAgencyId }
     *     
     */
    public UniqueAgencyId getUniqueAgencyId() {
        return uniqueAgencyId;
    }

    /**
     * Sets the value of the uniqueAgencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueAgencyId }
     *     
     */
    public void setUniqueAgencyId(UniqueAgencyId value) {
        this.uniqueAgencyId = value;
    }

    /**
     * Gets the value of the deleteAgencyFields property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteAgencyFields }
     *     
     */
    public DeleteAgencyFields getDeleteAgencyFields() {
        return deleteAgencyFields;
    }

    /**
     * Sets the value of the deleteAgencyFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteAgencyFields }
     *     
     */
    public void setDeleteAgencyFields(DeleteAgencyFields value) {
        this.deleteAgencyFields = value;
    }

    /**
     * Gets the value of the addAgencyFields property.
     * 
     * @return
     *     possible object is
     *     {@link AddAgencyFields }
     *     
     */
    public AddAgencyFields getAddAgencyFields() {
        return addAgencyFields;
    }

    /**
     * Sets the value of the addAgencyFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddAgencyFields }
     *     
     */
    public void setAddAgencyFields(AddAgencyFields value) {
        this.addAgencyFields = value;
    }

}
