//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "promptOutput",
    "promptInput"
})
@XmlRootElement(name = "AuthenticationPrompt")
public class AuthenticationPrompt {

    @XmlElement(name = "PromptOutput", required = true)
    protected PromptOutput promptOutput;
    @XmlElement(name = "PromptInput", required = true)
    protected PromptInput promptInput;

    /**
     * Gets the value of the promptOutput property.
     * 
     * @return
     *     possible object is
     *     {@link PromptOutput }
     *     
     */
    public PromptOutput getPromptOutput() {
        return promptOutput;
    }

    /**
     * Sets the value of the promptOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PromptOutput }
     *     
     */
    public void setPromptOutput(PromptOutput value) {
        this.promptOutput = value;
    }

    /**
     * Gets the value of the promptInput property.
     * 
     * @return
     *     possible object is
     *     {@link PromptInput }
     *     
     */
    public PromptInput getPromptInput() {
        return promptInput;
    }

    /**
     * Sets the value of the promptInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PromptInput }
     *     
     */
    public void setPromptInput(PromptInput value) {
        this.promptInput = value;
    }

}
