//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authenticationInputData",
    "authenticationDataFormatType",
    "authenticationInputType"
})
@XmlRootElement(name = "AuthenticationInput")
public class AuthenticationInput {

    @XmlElement(name = "AuthenticationInputData", required = true)
    protected AuthenticationInputData authenticationInputData;
    @XmlElement(name = "AuthenticationDataFormatType", required = true)
    protected AuthenticationDataFormatType authenticationDataFormatType;
    @XmlElement(name = "AuthenticationInputType", required = true)
    protected AuthenticationInputType authenticationInputType;

    /**
     * Gets the value of the authenticationInputData property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationInputData }
     *     
     */
    public AuthenticationInputData getAuthenticationInputData() {
        return authenticationInputData;
    }

    /**
     * Sets the value of the authenticationInputData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationInputData }
     *     
     */
    public void setAuthenticationInputData(AuthenticationInputData value) {
        this.authenticationInputData = value;
    }

    /**
     * Gets the value of the authenticationDataFormatType property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationDataFormatType }
     *     
     */
    public AuthenticationDataFormatType getAuthenticationDataFormatType() {
        return authenticationDataFormatType;
    }

    /**
     * Sets the value of the authenticationDataFormatType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationDataFormatType }
     *     
     */
    public void setAuthenticationDataFormatType(AuthenticationDataFormatType value) {
        this.authenticationDataFormatType = value;
    }

    /**
     * Gets the value of the authenticationInputType property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationInputType }
     *     
     */
    public AuthenticationInputType getAuthenticationInputType() {
        return authenticationInputType;
    }

    /**
     * Sets the value of the authenticationInputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationInputType }
     *     
     */
    public void setAuthenticationInputType(AuthenticationInputType value) {
        this.authenticationInputType = value;
    }

}
