//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bibliographicRecordIdentifier",
    "uniqueAgencyIdOrBibliographicRecordIdentifierCode"
})
@XmlRootElement(name = "BibliographicRecordId")
public class BibliographicRecordId {

    @XmlElement(name = "BibliographicRecordIdentifier", required = true)
    protected BibliographicRecordIdentifier bibliographicRecordIdentifier;
    @XmlElements({
        @XmlElement(name = "UniqueAgencyId", required = true, type = UniqueAgencyId.class),
        @XmlElement(name = "BibliographicRecordIdentifierCode", required = true, type = BibliographicRecordIdentifierCode.class)
    })
    protected List<Object> uniqueAgencyIdOrBibliographicRecordIdentifierCode;

    /**
     * Gets the value of the bibliographicRecordIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicRecordIdentifier }
     *     
     */
    public BibliographicRecordIdentifier getBibliographicRecordIdentifier() {
        return bibliographicRecordIdentifier;
    }

    /**
     * Sets the value of the bibliographicRecordIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicRecordIdentifier }
     *     
     */
    public void setBibliographicRecordIdentifier(BibliographicRecordIdentifier value) {
        this.bibliographicRecordIdentifier = value;
    }

    /**
     * Gets the value of the uniqueAgencyIdOrBibliographicRecordIdentifierCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uniqueAgencyIdOrBibliographicRecordIdentifierCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniqueAgencyIdOrBibliographicRecordIdentifierCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UniqueAgencyId }
     * {@link BibliographicRecordIdentifierCode }
     * 
     * 
     */
    public List<Object> getUniqueAgencyIdOrBibliographicRecordIdentifierCode() {
        if (uniqueAgencyIdOrBibliographicRecordIdentifierCode == null) {
            uniqueAgencyIdOrBibliographicRecordIdentifierCode = new ArrayList<Object>();
        }
        return this.uniqueAgencyIdOrBibliographicRecordIdentifierCode;
    }

}
