//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "author",
    "authorOfComponent",
    "bibliographicItemId",
    "bibliographicRecordId",
    "componentId",
    "edition",
    "pagination",
    "placeOfPublication",
    "publicationDate",
    "publicationDateOfComponent",
    "publisher",
    "seriesTitleNumber",
    "title",
    "titleOfComponent",
    "bibliographicLevel",
    "sponsoringBody",
    "electronicDataFormatType",
    "language",
    "mediumType"
})
@XmlRootElement(name = "BibliographicDescription")
public class BibliographicDescription {

    @XmlElement(name = "Author")
    protected Author author;
    @XmlElement(name = "AuthorOfComponent")
    protected AuthorOfComponent authorOfComponent;
    @XmlElement(name = "BibliographicItemId")
    protected BibliographicItemId bibliographicItemId;
    @XmlElement(name = "BibliographicRecordId")
    protected BibliographicRecordId bibliographicRecordId;
    @XmlElement(name = "ComponentId")
    protected ComponentId componentId;
    @XmlElement(name = "Edition")
    protected Edition edition;
    @XmlElement(name = "Pagination")
    protected Pagination pagination;
    @XmlElement(name = "PlaceOfPublication")
    protected PlaceOfPublication placeOfPublication;
    @XmlElement(name = "PublicationDate")
    protected PublicationDate publicationDate;
    @XmlElement(name = "PublicationDateOfComponent")
    protected PublicationDateOfComponent publicationDateOfComponent;
    @XmlElement(name = "Publisher")
    protected Publisher publisher;
    @XmlElement(name = "SeriesTitleNumber")
    protected SeriesTitleNumber seriesTitleNumber;
    @XmlElement(name = "Title")
    protected Title title;
    @XmlElement(name = "TitleOfComponent")
    protected TitleOfComponent titleOfComponent;
    @XmlElement(name = "BibliographicLevel")
    protected BibliographicLevel bibliographicLevel;
    @XmlElement(name = "SponsoringBody")
    protected SponsoringBody sponsoringBody;
    @XmlElement(name = "ElectronicDataFormatType")
    protected ElectronicDataFormatType electronicDataFormatType;
    @XmlElement(name = "Language")
    protected Language language;
    @XmlElement(name = "MediumType")
    protected MediumType mediumType;

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link Author }
     *     
     */
    public Author getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link Author }
     *     
     */
    public void setAuthor(Author value) {
        this.author = value;
    }

    /**
     * Gets the value of the authorOfComponent property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorOfComponent }
     *     
     */
    public AuthorOfComponent getAuthorOfComponent() {
        return authorOfComponent;
    }

    /**
     * Sets the value of the authorOfComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorOfComponent }
     *     
     */
    public void setAuthorOfComponent(AuthorOfComponent value) {
        this.authorOfComponent = value;
    }

    /**
     * Gets the value of the bibliographicItemId property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicItemId }
     *     
     */
    public BibliographicItemId getBibliographicItemId() {
        return bibliographicItemId;
    }

    /**
     * Sets the value of the bibliographicItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicItemId }
     *     
     */
    public void setBibliographicItemId(BibliographicItemId value) {
        this.bibliographicItemId = value;
    }

    /**
     * Gets the value of the bibliographicRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicRecordId }
     *     
     */
    public BibliographicRecordId getBibliographicRecordId() {
        return bibliographicRecordId;
    }

    /**
     * Sets the value of the bibliographicRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicRecordId }
     *     
     */
    public void setBibliographicRecordId(BibliographicRecordId value) {
        this.bibliographicRecordId = value;
    }

    /**
     * Gets the value of the componentId property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentId }
     *     
     */
    public ComponentId getComponentId() {
        return componentId;
    }

    /**
     * Sets the value of the componentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentId }
     *     
     */
    public void setComponentId(ComponentId value) {
        this.componentId = value;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link Edition }
     *     
     */
    public Edition getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Edition }
     *     
     */
    public void setEdition(Edition value) {
        this.edition = value;
    }

    /**
     * Gets the value of the pagination property.
     * 
     * @return
     *     possible object is
     *     {@link Pagination }
     *     
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagination }
     *     
     */
    public void setPagination(Pagination value) {
        this.pagination = value;
    }

    /**
     * Gets the value of the placeOfPublication property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceOfPublication }
     *     
     */
    public PlaceOfPublication getPlaceOfPublication() {
        return placeOfPublication;
    }

    /**
     * Sets the value of the placeOfPublication property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceOfPublication }
     *     
     */
    public void setPlaceOfPublication(PlaceOfPublication value) {
        this.placeOfPublication = value;
    }

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationDate }
     *     
     */
    public PublicationDate getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationDate }
     *     
     */
    public void setPublicationDate(PublicationDate value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the publicationDateOfComponent property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationDateOfComponent }
     *     
     */
    public PublicationDateOfComponent getPublicationDateOfComponent() {
        return publicationDateOfComponent;
    }

    /**
     * Sets the value of the publicationDateOfComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationDateOfComponent }
     *     
     */
    public void setPublicationDateOfComponent(PublicationDateOfComponent value) {
        this.publicationDateOfComponent = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link Publisher }
     *     
     */
    public Publisher getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publisher }
     *     
     */
    public void setPublisher(Publisher value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the seriesTitleNumber property.
     * 
     * @return
     *     possible object is
     *     {@link SeriesTitleNumber }
     *     
     */
    public SeriesTitleNumber getSeriesTitleNumber() {
        return seriesTitleNumber;
    }

    /**
     * Sets the value of the seriesTitleNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeriesTitleNumber }
     *     
     */
    public void setSeriesTitleNumber(SeriesTitleNumber value) {
        this.seriesTitleNumber = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Title }
     *     
     */
    public Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Title }
     *     
     */
    public void setTitle(Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the titleOfComponent property.
     * 
     * @return
     *     possible object is
     *     {@link TitleOfComponent }
     *     
     */
    public TitleOfComponent getTitleOfComponent() {
        return titleOfComponent;
    }

    /**
     * Sets the value of the titleOfComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleOfComponent }
     *     
     */
    public void setTitleOfComponent(TitleOfComponent value) {
        this.titleOfComponent = value;
    }

    /**
     * Gets the value of the bibliographicLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicLevel }
     *     
     */
    public BibliographicLevel getBibliographicLevel() {
        return bibliographicLevel;
    }

    /**
     * Sets the value of the bibliographicLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicLevel }
     *     
     */
    public void setBibliographicLevel(BibliographicLevel value) {
        this.bibliographicLevel = value;
    }

    /**
     * Gets the value of the sponsoringBody property.
     * 
     * @return
     *     possible object is
     *     {@link SponsoringBody }
     *     
     */
    public SponsoringBody getSponsoringBody() {
        return sponsoringBody;
    }

    /**
     * Sets the value of the sponsoringBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link SponsoringBody }
     *     
     */
    public void setSponsoringBody(SponsoringBody value) {
        this.sponsoringBody = value;
    }

    /**
     * Gets the value of the electronicDataFormatType property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicDataFormatType }
     *     
     */
    public ElectronicDataFormatType getElectronicDataFormatType() {
        return electronicDataFormatType;
    }

    /**
     * Sets the value of the electronicDataFormatType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicDataFormatType }
     *     
     */
    public void setElectronicDataFormatType(ElectronicDataFormatType value) {
        this.electronicDataFormatType = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Language }
     *     
     */
    public Language getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Language }
     *     
     */
    public void setLanguage(Language value) {
        this.language = value;
    }

    /**
     * Gets the value of the mediumType property.
     * 
     * @return
     *     possible object is
     *     {@link MediumType }
     *     
     */
    public MediumType getMediumType() {
        return mediumType;
    }

    /**
     * Sets the value of the mediumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediumType }
     *     
     */
    public void setMediumType(MediumType value) {
        this.mediumType = value;
    }

}
