//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bibliographicItemIdentifier",
    "bibliographicItemIdentifierCode"
})
@XmlRootElement(name = "BibliographicItemId")
public class BibliographicItemId {

    @XmlElement(name = "BibliographicItemIdentifier", required = true)
    protected BibliographicItemIdentifier bibliographicItemIdentifier;
    @XmlElement(name = "BibliographicItemIdentifierCode")
    protected BibliographicItemIdentifierCode bibliographicItemIdentifierCode;

    /**
     * Gets the value of the bibliographicItemIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicItemIdentifier }
     *     
     */
    public BibliographicItemIdentifier getBibliographicItemIdentifier() {
        return bibliographicItemIdentifier;
    }

    /**
     * Sets the value of the bibliographicItemIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicItemIdentifier }
     *     
     */
    public void setBibliographicItemIdentifier(BibliographicItemIdentifier value) {
        this.bibliographicItemIdentifier = value;
    }

    /**
     * Gets the value of the bibliographicItemIdentifierCode property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicItemIdentifierCode }
     *     
     */
    public BibliographicItemIdentifierCode getBibliographicItemIdentifierCode() {
        return bibliographicItemIdentifierCode;
    }

    /**
     * Sets the value of the bibliographicItemIdentifierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicItemIdentifierCode }
     *     
     */
    public void setBibliographicItemIdentifierCode(BibliographicItemIdentifierCode value) {
        this.bibliographicItemIdentifierCode = value;
    }

}
