//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiationHeader",
    "mandatedAction",
    "uniqueUserIdOrAuthenticationInput",
    "uniqueItemId",
    "uniqueRequestId",
    "acknowledgedFeeAmount",
    "acknowledgedItemUseRestrictionType",
    "shippingInformation",
    "resourceDesired",
    "desiredDateDue",
    "itemElementType",
    "userElementType"
})
@XmlRootElement(name = "CheckOutItem")
public class CheckOutItem {

    @XmlElement(name = "InitiationHeader", required = true)
    protected InitiationHeader initiationHeader;
    @XmlElement(name = "MandatedAction")
    protected MandatedAction mandatedAction;
    @XmlElements({
        @XmlElement(name = "UniqueUserId", required = true, type = UniqueUserId.class),
        @XmlElement(name = "AuthenticationInput", required = true, type = AuthenticationInput.class)
    })
    protected List<Object> uniqueUserIdOrAuthenticationInput;
    @XmlElement(name = "UniqueItemId", required = true)
    protected UniqueItemId uniqueItemId;
    @XmlElement(name = "UniqueRequestId")
    protected UniqueRequestId uniqueRequestId;
    @XmlElement(name = "AcknowledgedFeeAmount")
    protected AcknowledgedFeeAmount acknowledgedFeeAmount;
    @XmlElement(name = "AcknowledgedItemUseRestrictionType")
    protected List<AcknowledgedItemUseRestrictionType> acknowledgedItemUseRestrictionType;
    @XmlElement(name = "ShippingInformation")
    protected ShippingInformation shippingInformation;
    @XmlElement(name = "ResourceDesired")
    protected ResourceDesired resourceDesired;
    @XmlElement(name = "DesiredDateDue")
    protected DesiredDateDue desiredDateDue;
    @XmlElement(name = "ItemElementType")
    protected List<ItemElementType> itemElementType;
    @XmlElement(name = "UserElementType")
    protected List<UserElementType> userElementType;

    /**
     * Gets the value of the initiationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InitiationHeader }
     *     
     */
    public InitiationHeader getInitiationHeader() {
        return initiationHeader;
    }

    /**
     * Sets the value of the initiationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiationHeader }
     *     
     */
    public void setInitiationHeader(InitiationHeader value) {
        this.initiationHeader = value;
    }

    /**
     * Gets the value of the mandatedAction property.
     * 
     * @return
     *     possible object is
     *     {@link MandatedAction }
     *     
     */
    public MandatedAction getMandatedAction() {
        return mandatedAction;
    }

    /**
     * Sets the value of the mandatedAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandatedAction }
     *     
     */
    public void setMandatedAction(MandatedAction value) {
        this.mandatedAction = value;
    }

    /**
     * Gets the value of the uniqueUserIdOrAuthenticationInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uniqueUserIdOrAuthenticationInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniqueUserIdOrAuthenticationInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UniqueUserId }
     * {@link AuthenticationInput }
     * 
     * 
     */
    public List<Object> getUniqueUserIdOrAuthenticationInput() {
        if (uniqueUserIdOrAuthenticationInput == null) {
            uniqueUserIdOrAuthenticationInput = new ArrayList<Object>();
        }
        return this.uniqueUserIdOrAuthenticationInput;
    }

    /**
     * Gets the value of the uniqueItemId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueItemId }
     *     
     */
    public UniqueItemId getUniqueItemId() {
        return uniqueItemId;
    }

    /**
     * Sets the value of the uniqueItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueItemId }
     *     
     */
    public void setUniqueItemId(UniqueItemId value) {
        this.uniqueItemId = value;
    }

    /**
     * Gets the value of the uniqueRequestId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueRequestId }
     *     
     */
    public UniqueRequestId getUniqueRequestId() {
        return uniqueRequestId;
    }

    /**
     * Sets the value of the uniqueRequestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueRequestId }
     *     
     */
    public void setUniqueRequestId(UniqueRequestId value) {
        this.uniqueRequestId = value;
    }

    /**
     * Gets the value of the acknowledgedFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AcknowledgedFeeAmount }
     *     
     */
    public AcknowledgedFeeAmount getAcknowledgedFeeAmount() {
        return acknowledgedFeeAmount;
    }

    /**
     * Sets the value of the acknowledgedFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcknowledgedFeeAmount }
     *     
     */
    public void setAcknowledgedFeeAmount(AcknowledgedFeeAmount value) {
        this.acknowledgedFeeAmount = value;
    }

    /**
     * Gets the value of the acknowledgedItemUseRestrictionType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acknowledgedItemUseRestrictionType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcknowledgedItemUseRestrictionType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcknowledgedItemUseRestrictionType }
     * 
     * 
     */
    public List<AcknowledgedItemUseRestrictionType> getAcknowledgedItemUseRestrictionType() {
        if (acknowledgedItemUseRestrictionType == null) {
            acknowledgedItemUseRestrictionType = new ArrayList<AcknowledgedItemUseRestrictionType>();
        }
        return this.acknowledgedItemUseRestrictionType;
    }

    /**
     * Gets the value of the shippingInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingInformation }
     *     
     */
    public ShippingInformation getShippingInformation() {
        return shippingInformation;
    }

    /**
     * Sets the value of the shippingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingInformation }
     *     
     */
    public void setShippingInformation(ShippingInformation value) {
        this.shippingInformation = value;
    }

    /**
     * Gets the value of the resourceDesired property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceDesired }
     *     
     */
    public ResourceDesired getResourceDesired() {
        return resourceDesired;
    }

    /**
     * Sets the value of the resourceDesired property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceDesired }
     *     
     */
    public void setResourceDesired(ResourceDesired value) {
        this.resourceDesired = value;
    }

    /**
     * Gets the value of the desiredDateDue property.
     * 
     * @return
     *     possible object is
     *     {@link DesiredDateDue }
     *     
     */
    public DesiredDateDue getDesiredDateDue() {
        return desiredDateDue;
    }

    /**
     * Sets the value of the desiredDateDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesiredDateDue }
     *     
     */
    public void setDesiredDateDue(DesiredDateDue value) {
        this.desiredDateDue = value;
    }

    /**
     * Gets the value of the itemElementType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemElementType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemElementType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemElementType }
     * 
     * 
     */
    public List<ItemElementType> getItemElementType() {
        if (itemElementType == null) {
            itemElementType = new ArrayList<ItemElementType>();
        }
        return this.itemElementType;
    }

    /**
     * Gets the value of the userElementType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userElementType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserElementType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserElementType }
     * 
     * 
     */
    public List<UserElementType> getUserElementType() {
        if (userElementType == null) {
            userElementType = new ArrayList<UserElementType>();
        }
        return this.userElementType;
    }

}
