//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chronologyCaptionOrChronologyLevel",
    "chronologyValue"
})
@XmlRootElement(name = "ChronologyLevelInstance")
public class ChronologyLevelInstance {

    @XmlElements({
        @XmlElement(name = "ChronologyCaption", required = true, type = ChronologyCaption.class),
        @XmlElement(name = "ChronologyLevel", required = true, type = ChronologyLevel.class)
    })
    protected List<Object> chronologyCaptionOrChronologyLevel;
    @XmlElement(name = "ChronologyValue", required = true)
    protected ChronologyValue chronologyValue;

    /**
     * Gets the value of the chronologyCaptionOrChronologyLevel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chronologyCaptionOrChronologyLevel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChronologyCaptionOrChronologyLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChronologyCaption }
     * {@link ChronologyLevel }
     * 
     * 
     */
    public List<Object> getChronologyCaptionOrChronologyLevel() {
        if (chronologyCaptionOrChronologyLevel == null) {
            chronologyCaptionOrChronologyLevel = new ArrayList<Object>();
        }
        return this.chronologyCaptionOrChronologyLevel;
    }

    /**
     * Gets the value of the chronologyValue property.
     * 
     * @return
     *     possible object is
     *     {@link ChronologyValue }
     *     
     */
    public ChronologyValue getChronologyValue() {
        return chronologyValue;
    }

    /**
     * Sets the value of the chronologyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChronologyValue }
     *     
     */
    public void setChronologyValue(ChronologyValue value) {
        this.chronologyValue = value;
    }

}
