//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "componentIdentifierType",
    "componentIdentifier"
})
@XmlRootElement(name = "ComponentId")
public class ComponentId {

    @XmlElement(name = "ComponentIdentifierType", required = true)
    protected ComponentIdentifierType componentIdentifierType;
    @XmlElement(name = "ComponentIdentifier", required = true)
    protected ComponentIdentifier componentIdentifier;

    /**
     * Gets the value of the componentIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentIdentifierType }
     *     
     */
    public ComponentIdentifierType getComponentIdentifierType() {
        return componentIdentifierType;
    }

    /**
     * Sets the value of the componentIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentIdentifierType }
     *     
     */
    public void setComponentIdentifierType(ComponentIdentifierType value) {
        this.componentIdentifierType = value;
    }

    /**
     * Gets the value of the componentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentIdentifier }
     *     
     */
    public ComponentIdentifier getComponentIdentifier() {
        return componentIdentifier;
    }

    /**
     * Sets the value of the componentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentIdentifier }
     *     
     */
    public void setComponentIdentifier(ComponentIdentifier value) {
        this.componentIdentifier = value;
    }

}
