//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "electronicAddressType",
    "electronicAddressData"
})
@XmlRootElement(name = "ElectronicAddress")
public class ElectronicAddress {

    @XmlElement(name = "ElectronicAddressType", required = true)
    protected ElectronicAddressType electronicAddressType;
    @XmlElement(name = "ElectronicAddressData", required = true)
    protected ElectronicAddressData electronicAddressData;

    /**
     * Gets the value of the electronicAddressType property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicAddressType }
     *     
     */
    public ElectronicAddressType getElectronicAddressType() {
        return electronicAddressType;
    }

    /**
     * Sets the value of the electronicAddressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicAddressType }
     *     
     */
    public void setElectronicAddressType(ElectronicAddressType value) {
        this.electronicAddressType = value;
    }

    /**
     * Gets the value of the electronicAddressData property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicAddressData }
     *     
     */
    public ElectronicAddressData getElectronicAddressData() {
        return electronicAddressData;
    }

    /**
     * Sets the value of the electronicAddressData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicAddressData }
     *     
     */
    public void setElectronicAddressData(ElectronicAddressData value) {
        this.electronicAddressData = value;
    }

}
