//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fiscalActionType",
    "fiscalTransactionReferenceId",
    "relatedFiscalTransactionReferenceId",
    "fiscalTransactionType",
    "validFromDate",
    "validToDate",
    "amount",
    "paymentMethodType",
    "fiscalTransactionDescription",
    "uniqueRequestId",
    "itemDetails"
})
@XmlRootElement(name = "FiscalTransactionInformation")
public class FiscalTransactionInformation {

    @XmlElement(name = "FiscalActionType", required = true)
    protected FiscalActionType fiscalActionType;
    @XmlElement(name = "FiscalTransactionReferenceId")
    protected FiscalTransactionReferenceId fiscalTransactionReferenceId;
    @XmlElement(name = "RelatedFiscalTransactionReferenceId")
    protected List<RelatedFiscalTransactionReferenceId> relatedFiscalTransactionReferenceId;
    @XmlElement(name = "FiscalTransactionType", required = true)
    protected FiscalTransactionType fiscalTransactionType;
    @XmlElement(name = "ValidFromDate")
    protected ValidFromDate validFromDate;
    @XmlElement(name = "ValidToDate")
    protected ValidToDate validToDate;
    @XmlElement(name = "Amount", required = true)
    protected Amount amount;
    @XmlElement(name = "PaymentMethodType")
    protected PaymentMethodType paymentMethodType;
    @XmlElement(name = "FiscalTransactionDescription")
    protected FiscalTransactionDescription fiscalTransactionDescription;
    @XmlElement(name = "UniqueRequestId")
    protected UniqueRequestId uniqueRequestId;
    @XmlElement(name = "ItemDetails")
    protected ItemDetails itemDetails;

    /**
     * Gets the value of the fiscalActionType property.
     * 
     * @return
     *     possible object is
     *     {@link FiscalActionType }
     *     
     */
    public FiscalActionType getFiscalActionType() {
        return fiscalActionType;
    }

    /**
     * Sets the value of the fiscalActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiscalActionType }
     *     
     */
    public void setFiscalActionType(FiscalActionType value) {
        this.fiscalActionType = value;
    }

    /**
     * Gets the value of the fiscalTransactionReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link FiscalTransactionReferenceId }
     *     
     */
    public FiscalTransactionReferenceId getFiscalTransactionReferenceId() {
        return fiscalTransactionReferenceId;
    }

    /**
     * Sets the value of the fiscalTransactionReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiscalTransactionReferenceId }
     *     
     */
    public void setFiscalTransactionReferenceId(FiscalTransactionReferenceId value) {
        this.fiscalTransactionReferenceId = value;
    }

    /**
     * Gets the value of the relatedFiscalTransactionReferenceId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedFiscalTransactionReferenceId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedFiscalTransactionReferenceId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedFiscalTransactionReferenceId }
     * 
     * 
     */
    public List<RelatedFiscalTransactionReferenceId> getRelatedFiscalTransactionReferenceId() {
        if (relatedFiscalTransactionReferenceId == null) {
            relatedFiscalTransactionReferenceId = new ArrayList<RelatedFiscalTransactionReferenceId>();
        }
        return this.relatedFiscalTransactionReferenceId;
    }

    /**
     * Gets the value of the fiscalTransactionType property.
     * 
     * @return
     *     possible object is
     *     {@link FiscalTransactionType }
     *     
     */
    public FiscalTransactionType getFiscalTransactionType() {
        return fiscalTransactionType;
    }

    /**
     * Sets the value of the fiscalTransactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiscalTransactionType }
     *     
     */
    public void setFiscalTransactionType(FiscalTransactionType value) {
        this.fiscalTransactionType = value;
    }

    /**
     * Gets the value of the validFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link ValidFromDate }
     *     
     */
    public ValidFromDate getValidFromDate() {
        return validFromDate;
    }

    /**
     * Sets the value of the validFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidFromDate }
     *     
     */
    public void setValidFromDate(ValidFromDate value) {
        this.validFromDate = value;
    }

    /**
     * Gets the value of the validToDate property.
     * 
     * @return
     *     possible object is
     *     {@link ValidToDate }
     *     
     */
    public ValidToDate getValidToDate() {
        return validToDate;
    }

    /**
     * Sets the value of the validToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidToDate }
     *     
     */
    public void setValidToDate(ValidToDate value) {
        this.validToDate = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmount(Amount value) {
        this.amount = value;
    }

    /**
     * Gets the value of the paymentMethodType property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethodType }
     *     
     */
    public PaymentMethodType getPaymentMethodType() {
        return paymentMethodType;
    }

    /**
     * Sets the value of the paymentMethodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethodType }
     *     
     */
    public void setPaymentMethodType(PaymentMethodType value) {
        this.paymentMethodType = value;
    }

    /**
     * Gets the value of the fiscalTransactionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link FiscalTransactionDescription }
     *     
     */
    public FiscalTransactionDescription getFiscalTransactionDescription() {
        return fiscalTransactionDescription;
    }

    /**
     * Sets the value of the fiscalTransactionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiscalTransactionDescription }
     *     
     */
    public void setFiscalTransactionDescription(FiscalTransactionDescription value) {
        this.fiscalTransactionDescription = value;
    }

    /**
     * Gets the value of the uniqueRequestId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueRequestId }
     *     
     */
    public UniqueRequestId getUniqueRequestId() {
        return uniqueRequestId;
    }

    /**
     * Sets the value of the uniqueRequestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueRequestId }
     *     
     */
    public void setUniqueRequestId(UniqueRequestId value) {
        this.uniqueRequestId = value;
    }

    /**
     * Gets the value of the itemDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ItemDetails }
     *     
     */
    public ItemDetails getItemDetails() {
        return itemDetails;
    }

    /**
     * Sets the value of the itemDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemDetails }
     *     
     */
    public void setItemDetails(ItemDetails value) {
        this.itemDetails = value;
    }

}
