//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "visibleItemId",
    "callNumber",
    "copyNumber",
    "itemDescriptionLevel",
    "holdingsInformation"
})
@XmlRootElement(name = "ItemDescription")
public class ItemDescription {

    @XmlElement(name = "VisibleItemId")
    protected VisibleItemId visibleItemId;
    @XmlElement(name = "CallNumber")
    protected CallNumber callNumber;
    @XmlElement(name = "CopyNumber")
    protected CopyNumber copyNumber;
    @XmlElement(name = "ItemDescriptionLevel")
    protected ItemDescriptionLevel itemDescriptionLevel;
    @XmlElement(name = "HoldingsInformation")
    protected HoldingsInformation holdingsInformation;

    /**
     * Gets the value of the visibleItemId property.
     * 
     * @return
     *     possible object is
     *     {@link VisibleItemId }
     *     
     */
    public VisibleItemId getVisibleItemId() {
        return visibleItemId;
    }

    /**
     * Sets the value of the visibleItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibleItemId }
     *     
     */
    public void setVisibleItemId(VisibleItemId value) {
        this.visibleItemId = value;
    }

    /**
     * Gets the value of the callNumber property.
     * 
     * @return
     *     possible object is
     *     {@link CallNumber }
     *     
     */
    public CallNumber getCallNumber() {
        return callNumber;
    }

    /**
     * Sets the value of the callNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallNumber }
     *     
     */
    public void setCallNumber(CallNumber value) {
        this.callNumber = value;
    }

    /**
     * Gets the value of the copyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link CopyNumber }
     *     
     */
    public CopyNumber getCopyNumber() {
        return copyNumber;
    }

    /**
     * Sets the value of the copyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link CopyNumber }
     *     
     */
    public void setCopyNumber(CopyNumber value) {
        this.copyNumber = value;
    }

    /**
     * Gets the value of the itemDescriptionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ItemDescriptionLevel }
     *     
     */
    public ItemDescriptionLevel getItemDescriptionLevel() {
        return itemDescriptionLevel;
    }

    /**
     * Sets the value of the itemDescriptionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemDescriptionLevel }
     *     
     */
    public void setItemDescriptionLevel(ItemDescriptionLevel value) {
        this.itemDescriptionLevel = value;
    }

    /**
     * Gets the value of the holdingsInformation property.
     * 
     * @return
     *     possible object is
     *     {@link HoldingsInformation }
     *     
     */
    public HoldingsInformation getHoldingsInformation() {
        return holdingsInformation;
    }

    /**
     * Sets the value of the holdingsInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link HoldingsInformation }
     *     
     */
    public void setHoldingsInformation(HoldingsInformation value) {
        this.holdingsInformation = value;
    }

}
