//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiationHeader",
    "uniqueUserIdOrUniqueItemIdOrRequestTypeOrUniqueRequestId",
    "deleteRequestFields",
    "addRequestFields",
    "itemOptionalFields",
    "userOptionalFields"
})
@XmlRootElement(name = "ItemRequestUpdated")
public class ItemRequestUpdated {

    @XmlElement(name = "InitiationHeader", required = true)
    protected InitiationHeader initiationHeader;
    @XmlElements({
        @XmlElement(name = "UniqueUserId", required = true, type = UniqueUserId.class),
        @XmlElement(name = "UniqueItemId", required = true, type = UniqueItemId.class),
        @XmlElement(name = "RequestType", required = true, type = RequestType.class),
        @XmlElement(name = "UniqueRequestId", required = true, type = UniqueRequestId.class)
    })
    protected List<Object> uniqueUserIdOrUniqueItemIdOrRequestTypeOrUniqueRequestId;
    @XmlElement(name = "DeleteRequestFields")
    protected DeleteRequestFields deleteRequestFields;
    @XmlElement(name = "AddRequestFields")
    protected AddRequestFields addRequestFields;
    @XmlElement(name = "ItemOptionalFields")
    protected ItemOptionalFields itemOptionalFields;
    @XmlElement(name = "UserOptionalFields")
    protected UserOptionalFields userOptionalFields;

    /**
     * Gets the value of the initiationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InitiationHeader }
     *     
     */
    public InitiationHeader getInitiationHeader() {
        return initiationHeader;
    }

    /**
     * Sets the value of the initiationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiationHeader }
     *     
     */
    public void setInitiationHeader(InitiationHeader value) {
        this.initiationHeader = value;
    }

    /**
     * Gets the value of the uniqueUserIdOrUniqueItemIdOrRequestTypeOrUniqueRequestId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uniqueUserIdOrUniqueItemIdOrRequestTypeOrUniqueRequestId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniqueUserIdOrUniqueItemIdOrRequestTypeOrUniqueRequestId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UniqueUserId }
     * {@link UniqueItemId }
     * {@link RequestType }
     * {@link UniqueRequestId }
     * 
     * 
     */
    public List<Object> getUniqueUserIdOrUniqueItemIdOrRequestTypeOrUniqueRequestId() {
        if (uniqueUserIdOrUniqueItemIdOrRequestTypeOrUniqueRequestId == null) {
            uniqueUserIdOrUniqueItemIdOrRequestTypeOrUniqueRequestId = new ArrayList<Object>();
        }
        return this.uniqueUserIdOrUniqueItemIdOrRequestTypeOrUniqueRequestId;
    }

    /**
     * Gets the value of the deleteRequestFields property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteRequestFields }
     *     
     */
    public DeleteRequestFields getDeleteRequestFields() {
        return deleteRequestFields;
    }

    /**
     * Sets the value of the deleteRequestFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteRequestFields }
     *     
     */
    public void setDeleteRequestFields(DeleteRequestFields value) {
        this.deleteRequestFields = value;
    }

    /**
     * Gets the value of the addRequestFields property.
     * 
     * @return
     *     possible object is
     *     {@link AddRequestFields }
     *     
     */
    public AddRequestFields getAddRequestFields() {
        return addRequestFields;
    }

    /**
     * Sets the value of the addRequestFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddRequestFields }
     *     
     */
    public void setAddRequestFields(AddRequestFields value) {
        this.addRequestFields = value;
    }

    /**
     * Gets the value of the itemOptionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link ItemOptionalFields }
     *     
     */
    public ItemOptionalFields getItemOptionalFields() {
        return itemOptionalFields;
    }

    /**
     * Sets the value of the itemOptionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemOptionalFields }
     *     
     */
    public void setItemOptionalFields(ItemOptionalFields value) {
        this.itemOptionalFields = value;
    }

    /**
     * Gets the value of the userOptionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link UserOptionalFields }
     *     
     */
    public UserOptionalFields getUserOptionalFields() {
        return userOptionalFields;
    }

    /**
     * Sets the value of the userOptionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserOptionalFields }
     *     
     */
    public void setUserOptionalFields(UserOptionalFields value) {
        this.userOptionalFields = value;
    }

}
