//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueItemId",
    "bibliographicDescription",
    "dateCheckedOut",
    "dateRenewed",
    "dateDueOrIndeterminateLoanPeriodFlagOrNonReturnableFlag",
    "dateReturned"
})
@XmlRootElement(name = "ItemDetails")
public class ItemDetails {

    @XmlElement(name = "UniqueItemId", required = true)
    protected UniqueItemId uniqueItemId;
    @XmlElement(name = "BibliographicDescription", required = true)
    protected BibliographicDescription bibliographicDescription;
    @XmlElement(name = "DateCheckedOut")
    protected DateCheckedOut dateCheckedOut;
    @XmlElement(name = "DateRenewed")
    protected List<DateRenewed> dateRenewed;
    @XmlElements({
        @XmlElement(name = "DateDue", type = DateDue.class),
        @XmlElement(name = "IndeterminateLoanPeriodFlag", type = IndeterminateLoanPeriodFlag.class),
        @XmlElement(name = "NonReturnableFlag", type = NonReturnableFlag.class)
    })
    protected List<Object> dateDueOrIndeterminateLoanPeriodFlagOrNonReturnableFlag;
    @XmlElement(name = "DateReturned")
    protected DateReturned dateReturned;

    /**
     * Gets the value of the uniqueItemId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueItemId }
     *     
     */
    public UniqueItemId getUniqueItemId() {
        return uniqueItemId;
    }

    /**
     * Sets the value of the uniqueItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueItemId }
     *     
     */
    public void setUniqueItemId(UniqueItemId value) {
        this.uniqueItemId = value;
    }

    /**
     * Gets the value of the bibliographicDescription property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicDescription }
     *     
     */
    public BibliographicDescription getBibliographicDescription() {
        return bibliographicDescription;
    }

    /**
     * Sets the value of the bibliographicDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicDescription }
     *     
     */
    public void setBibliographicDescription(BibliographicDescription value) {
        this.bibliographicDescription = value;
    }

    /**
     * Gets the value of the dateCheckedOut property.
     * 
     * @return
     *     possible object is
     *     {@link DateCheckedOut }
     *     
     */
    public DateCheckedOut getDateCheckedOut() {
        return dateCheckedOut;
    }

    /**
     * Sets the value of the dateCheckedOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCheckedOut }
     *     
     */
    public void setDateCheckedOut(DateCheckedOut value) {
        this.dateCheckedOut = value;
    }

    /**
     * Gets the value of the dateRenewed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateRenewed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateRenewed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateRenewed }
     * 
     * 
     */
    public List<DateRenewed> getDateRenewed() {
        if (dateRenewed == null) {
            dateRenewed = new ArrayList<DateRenewed>();
        }
        return this.dateRenewed;
    }

    /**
     * Gets the value of the dateDueOrIndeterminateLoanPeriodFlagOrNonReturnableFlag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateDueOrIndeterminateLoanPeriodFlagOrNonReturnableFlag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateDueOrIndeterminateLoanPeriodFlagOrNonReturnableFlag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateDue }
     * {@link IndeterminateLoanPeriodFlag }
     * {@link NonReturnableFlag }
     * 
     * 
     */
    public List<Object> getDateDueOrIndeterminateLoanPeriodFlagOrNonReturnableFlag() {
        if (dateDueOrIndeterminateLoanPeriodFlagOrNonReturnableFlag == null) {
            dateDueOrIndeterminateLoanPeriodFlagOrNonReturnableFlag = new ArrayList<Object>();
        }
        return this.dateDueOrIndeterminateLoanPeriodFlagOrNonReturnableFlag;
    }

    /**
     * Gets the value of the dateReturned property.
     * 
     * @return
     *     possible object is
     *     {@link DateReturned }
     *     
     */
    public DateReturned getDateReturned() {
        return dateReturned;
    }

    /**
     * Sets the value of the dateReturned property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateReturned }
     *     
     */
    public void setDateReturned(DateReturned value) {
        this.dateReturned = value;
    }

}
