//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locationNameLevel",
    "locationNameValue"
})
@XmlRootElement(name = "LocationNameInstance")
public class LocationNameInstance {

    @XmlElement(name = "LocationNameLevel", required = true)
    protected LocationNameLevel locationNameLevel;
    @XmlElement(name = "LocationNameValue", required = true)
    protected LocationNameValue locationNameValue;

    /**
     * Gets the value of the locationNameLevel property.
     * 
     * @return
     *     possible object is
     *     {@link LocationNameLevel }
     *     
     */
    public LocationNameLevel getLocationNameLevel() {
        return locationNameLevel;
    }

    /**
     * Sets the value of the locationNameLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationNameLevel }
     *     
     */
    public void setLocationNameLevel(LocationNameLevel value) {
        this.locationNameLevel = value;
    }

    /**
     * Gets the value of the locationNameValue property.
     * 
     * @return
     *     possible object is
     *     {@link LocationNameValue }
     *     
     */
    public LocationNameValue getLocationNameValue() {
        return locationNameValue;
    }

    /**
     * Sets the value of the locationNameValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationNameValue }
     *     
     */
    public void setLocationNameValue(LocationNameValue value) {
        this.locationNameValue = value;
    }

}
