//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiationHeader",
    "uniqueUserIdOrVisibleUserIdOrAuthenticationInput",
    "userElementType",
    "loanedItemsDesired",
    "requestedItemsDesired",
    "userFiscalAccountDesired"
})
@XmlRootElement(name = "LookupUser")
public class LookupUser {

    @XmlElement(name = "InitiationHeader", required = true)
    protected InitiationHeader initiationHeader;
    @XmlElements({
        @XmlElement(name = "UniqueUserId", required = true, type = UniqueUserId.class),
        @XmlElement(name = "VisibleUserId", required = true, type = VisibleUserId.class),
        @XmlElement(name = "AuthenticationInput", required = true, type = AuthenticationInput.class)
    })
    protected List<Object> uniqueUserIdOrVisibleUserIdOrAuthenticationInput;
    @XmlElement(name = "UserElementType", required = true)
    protected List<UserElementType> userElementType;
    @XmlElement(name = "LoanedItemsDesired")
    protected LoanedItemsDesired loanedItemsDesired;
    @XmlElement(name = "RequestedItemsDesired")
    protected RequestedItemsDesired requestedItemsDesired;
    @XmlElement(name = "UserFiscalAccountDesired")
    protected UserFiscalAccountDesired userFiscalAccountDesired;

    /**
     * Gets the value of the initiationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InitiationHeader }
     *     
     */
    public InitiationHeader getInitiationHeader() {
        return initiationHeader;
    }

    /**
     * Sets the value of the initiationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiationHeader }
     *     
     */
    public void setInitiationHeader(InitiationHeader value) {
        this.initiationHeader = value;
    }

    /**
     * Gets the value of the uniqueUserIdOrVisibleUserIdOrAuthenticationInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uniqueUserIdOrVisibleUserIdOrAuthenticationInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniqueUserIdOrVisibleUserIdOrAuthenticationInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UniqueUserId }
     * {@link VisibleUserId }
     * {@link AuthenticationInput }
     * 
     * 
     */
    public List<Object> getUniqueUserIdOrVisibleUserIdOrAuthenticationInput() {
        if (uniqueUserIdOrVisibleUserIdOrAuthenticationInput == null) {
            uniqueUserIdOrVisibleUserIdOrAuthenticationInput = new ArrayList<Object>();
        }
        return this.uniqueUserIdOrVisibleUserIdOrAuthenticationInput;
    }

    /**
     * Gets the value of the userElementType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userElementType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserElementType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserElementType }
     * 
     * 
     */
    public List<UserElementType> getUserElementType() {
        if (userElementType == null) {
            userElementType = new ArrayList<UserElementType>();
        }
        return this.userElementType;
    }

    /**
     * Gets the value of the loanedItemsDesired property.
     * 
     * @return
     *     possible object is
     *     {@link LoanedItemsDesired }
     *     
     */
    public LoanedItemsDesired getLoanedItemsDesired() {
        return loanedItemsDesired;
    }

    /**
     * Sets the value of the loanedItemsDesired property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanedItemsDesired }
     *     
     */
    public void setLoanedItemsDesired(LoanedItemsDesired value) {
        this.loanedItemsDesired = value;
    }

    /**
     * Gets the value of the requestedItemsDesired property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedItemsDesired }
     *     
     */
    public RequestedItemsDesired getRequestedItemsDesired() {
        return requestedItemsDesired;
    }

    /**
     * Sets the value of the requestedItemsDesired property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedItemsDesired }
     *     
     */
    public void setRequestedItemsDesired(RequestedItemsDesired value) {
        this.requestedItemsDesired = value;
    }

    /**
     * Gets the value of the userFiscalAccountDesired property.
     * 
     * @return
     *     possible object is
     *     {@link UserFiscalAccountDesired }
     *     
     */
    public UserFiscalAccountDesired getUserFiscalAccountDesired() {
        return userFiscalAccountDesired;
    }

    /**
     * Sets the value of the userFiscalAccountDesired property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFiscalAccountDesired }
     *     
     */
    public void setUserFiscalAccountDesired(UserFiscalAccountDesired value) {
        this.userFiscalAccountDesired = value;
    }

}
