//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse"
})
@XmlRootElement(name = "NCIPMessage")
public class NCIPMessage {

    @XmlAttribute(name = "version", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlElements({
        @XmlElement(name = "AcceptItem", required = true, type = AcceptItem.class),
        @XmlElement(name = "AcceptItemResponse", required = true, type = AcceptItemResponse.class),
        @XmlElement(name = "AgencyCreated", required = true, type = AgencyCreated.class),
        @XmlElement(name = "AgencyCreatedResponse", required = true, type = AgencyCreatedResponse.class),
        @XmlElement(name = "AgencyUpdated", required = true, type = AgencyUpdated.class),
        @XmlElement(name = "AgencyUpdatedResponse", required = true, type = AgencyUpdatedResponse.class),
        @XmlElement(name = "AuthenticateUser", required = true, type = AuthenticateUser.class),
        @XmlElement(name = "AuthenticateUserResponse", required = true, type = AuthenticateUserResponse.class),
        @XmlElement(name = "CancelRecallItem", required = true, type = CancelRecallItem.class),
        @XmlElement(name = "CancelRecallItemResponse", required = true, type = CancelRecallItemResponse.class),
        @XmlElement(name = "CancelRequestItem", required = true, type = CancelRequestItem.class),
        @XmlElement(name = "CancelRequestItemResponse", required = true, type = CancelRequestItemResponse.class),
        @XmlElement(name = "CheckInItem", required = true, type = CheckInItem.class),
        @XmlElement(name = "CheckInItemResponse", required = true, type = CheckInItemResponse.class),
        @XmlElement(name = "CheckOutItem", required = true, type = CheckOutItem.class),
        @XmlElement(name = "CheckOutItemResponse", required = true, type = CheckOutItemResponse.class),
        @XmlElement(name = "CirculationStatusChangeReported", required = true, type = CirculationStatusChangeReported.class),
        @XmlElement(name = "CirculationStatusChangeReportedResponse", required = true, type = CirculationStatusChangeReportedResponse.class),
        @XmlElement(name = "CirculationStatusUpdated", required = true, type = CirculationStatusUpdated.class),
        @XmlElement(name = "CirculationStatusUpdatedResponse", required = true, type = CirculationStatusUpdatedResponse.class),
        @XmlElement(name = "CreateAgency", required = true, type = CreateAgency.class),
        @XmlElement(name = "CreateAgencyResponse", required = true, type = CreateAgencyResponse.class),
        @XmlElement(name = "CreateItem", required = true, type = CreateItem.class),
        @XmlElement(name = "CreateItemResponse", required = true, type = CreateItemResponse.class),
        @XmlElement(name = "CreateUser", required = true, type = CreateUser.class),
        @XmlElement(name = "CreateUserResponse", required = true, type = CreateUserResponse.class),
        @XmlElement(name = "CreateUserFiscalTransaction", required = true, type = CreateUserFiscalTransaction.class),
        @XmlElement(name = "CreateUserFiscalTransactionResponse", required = true, type = CreateUserFiscalTransactionResponse.class),
        @XmlElement(name = "ItemCheckedIn", required = true, type = ItemCheckedIn.class),
        @XmlElement(name = "ItemCheckedInResponse", required = true, type = ItemCheckedInResponse.class),
        @XmlElement(name = "ItemCheckedOut", required = true, type = ItemCheckedOut.class),
        @XmlElement(name = "ItemCheckedOutResponse", required = true, type = ItemCheckedOutResponse.class),
        @XmlElement(name = "ItemCreated", required = true, type = ItemCreated.class),
        @XmlElement(name = "ItemCreatedResponse", required = true, type = ItemCreatedResponse.class),
        @XmlElement(name = "ItemRecallCancelled", required = true, type = ItemRecallCancelled.class),
        @XmlElement(name = "ItemRecallCancelledResponse", required = true, type = ItemRecallCancelledResponse.class),
        @XmlElement(name = "ItemRecalled", required = true, type = ItemRecalled.class),
        @XmlElement(name = "ItemRecalledResponse", required = true, type = ItemRecalledResponse.class),
        @XmlElement(name = "ItemReceived", required = true, type = ItemReceived.class),
        @XmlElement(name = "ItemReceivedResponse", required = true, type = ItemReceivedResponse.class),
        @XmlElement(name = "ItemRenewed", required = true, type = ItemRenewed.class),
        @XmlElement(name = "ItemRenewedResponse", required = true, type = ItemRenewedResponse.class),
        @XmlElement(name = "ItemRequestCancelled", required = true, type = ItemRequestCancelled.class),
        @XmlElement(name = "ItemRequestCancelledResponse", required = true, type = ItemRequestCancelledResponse.class),
        @XmlElement(name = "ItemRequestUpdated", required = true, type = ItemRequestUpdated.class),
        @XmlElement(name = "ItemRequestUpdatedResponse", required = true, type = ItemRequestUpdatedResponse.class),
        @XmlElement(name = "ItemRequested", required = true, type = ItemRequested.class),
        @XmlElement(name = "ItemRequestedResponse", required = true, type = ItemRequestedResponse.class),
        @XmlElement(name = "ItemShipped", required = true, type = ItemShipped.class),
        @XmlElement(name = "ItemShippedResponse", required = true, type = ItemShippedResponse.class),
        @XmlElement(name = "ItemUpdated", required = true, type = ItemUpdated.class),
        @XmlElement(name = "ItemUpdatedResponse", required = true, type = ItemUpdatedResponse.class),
        @XmlElement(name = "LookupAgency", required = true, type = LookupAgency.class),
        @XmlElement(name = "LookupAgencyResponse", required = true, type = LookupAgencyResponse.class),
        @XmlElement(name = "LookupItem", required = true, type = LookupItem.class),
        @XmlElement(name = "LookupItemResponse", required = true, type = LookupItemResponse.class),
        @XmlElement(name = "LookupUser", required = true, type = LookupUser.class),
        @XmlElement(name = "LookupUserResponse", required = true, type = LookupUserResponse.class),
        @XmlElement(name = "RecallItem", required = true, type = RecallItem.class),
        @XmlElement(name = "RecallItemResponse", required = true, type = RecallItemResponse.class),
        @XmlElement(name = "RenewItem", required = true, type = RenewItem.class),
        @XmlElement(name = "RenewItemResponse", required = true, type = RenewItemResponse.class),
        @XmlElement(name = "ReportCirculationStatusChange", required = true, type = ReportCirculationStatusChange.class),
        @XmlElement(name = "ReportCirculationStatusChangeResponse", required = true, type = ReportCirculationStatusChangeResponse.class),
        @XmlElement(name = "RequestItem", required = true, type = RequestItem.class),
        @XmlElement(name = "RequestItemResponse", required = true, type = RequestItemResponse.class),
        @XmlElement(name = "SendUserNotice", required = true, type = SendUserNotice.class),
        @XmlElement(name = "SendUserNoticeResponse", required = true, type = SendUserNoticeResponse.class),
        @XmlElement(name = "UndoCheckOutItem", required = true, type = UndoCheckOutItem.class),
        @XmlElement(name = "UndoCheckOutItemResponse", required = true, type = UndoCheckOutItemResponse.class),
        @XmlElement(name = "UpdateAgency", required = true, type = UpdateAgency.class),
        @XmlElement(name = "UpdateAgencyResponse", required = true, type = UpdateAgencyResponse.class),
        @XmlElement(name = "UpdateCirculationStatus", required = true, type = UpdateCirculationStatus.class),
        @XmlElement(name = "UpdateCirculationStatusResponse", required = true, type = UpdateCirculationStatusResponse.class),
        @XmlElement(name = "UpdateItem", required = true, type = UpdateItem.class),
        @XmlElement(name = "UpdateItemResponse", required = true, type = UpdateItemResponse.class),
        @XmlElement(name = "UpdateRequestItem", required = true, type = UpdateRequestItem.class),
        @XmlElement(name = "UpdateRequestItemResponse", required = true, type = UpdateRequestItemResponse.class),
        @XmlElement(name = "UpdateUser", required = true, type = UpdateUser.class),
        @XmlElement(name = "UpdateUserResponse", required = true, type = UpdateUserResponse.class),
        @XmlElement(name = "UserCreated", required = true, type = UserCreated.class),
        @XmlElement(name = "UserCreatedResponse", required = true, type = UserCreatedResponse.class),
        @XmlElement(name = "UserFiscalTransactionCreated", required = true, type = UserFiscalTransactionCreated.class),
        @XmlElement(name = "UserFiscalTransactionCreatedResponse", required = true, type = UserFiscalTransactionCreatedResponse.class),
        @XmlElement(name = "UserNoticeSent", required = true, type = UserNoticeSent.class),
        @XmlElement(name = "UserNoticeSentResponse", required = true, type = UserNoticeSentResponse.class),
        @XmlElement(name = "UserUpdated", required = true, type = UserUpdated.class),
        @XmlElement(name = "UserUpdatedResponse", required = true, type = UserUpdatedResponse.class)
    })
    protected List<Object> acceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the acceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcceptItem }
     * {@link AcceptItemResponse }
     * {@link AgencyCreated }
     * {@link AgencyCreatedResponse }
     * {@link AgencyUpdated }
     * {@link AgencyUpdatedResponse }
     * {@link AuthenticateUser }
     * {@link AuthenticateUserResponse }
     * {@link CancelRecallItem }
     * {@link CancelRecallItemResponse }
     * {@link CancelRequestItem }
     * {@link CancelRequestItemResponse }
     * {@link CheckInItem }
     * {@link CheckInItemResponse }
     * {@link CheckOutItem }
     * {@link CheckOutItemResponse }
     * {@link CirculationStatusChangeReported }
     * {@link CirculationStatusChangeReportedResponse }
     * {@link CirculationStatusUpdated }
     * {@link CirculationStatusUpdatedResponse }
     * {@link CreateAgency }
     * {@link CreateAgencyResponse }
     * {@link CreateItem }
     * {@link CreateItemResponse }
     * {@link CreateUser }
     * {@link CreateUserResponse }
     * {@link CreateUserFiscalTransaction }
     * {@link CreateUserFiscalTransactionResponse }
     * {@link ItemCheckedIn }
     * {@link ItemCheckedInResponse }
     * {@link ItemCheckedOut }
     * {@link ItemCheckedOutResponse }
     * {@link ItemCreated }
     * {@link ItemCreatedResponse }
     * {@link ItemRecallCancelled }
     * {@link ItemRecallCancelledResponse }
     * {@link ItemRecalled }
     * {@link ItemRecalledResponse }
     * {@link ItemReceived }
     * {@link ItemReceivedResponse }
     * {@link ItemRenewed }
     * {@link ItemRenewedResponse }
     * {@link ItemRequestCancelled }
     * {@link ItemRequestCancelledResponse }
     * {@link ItemRequestUpdated }
     * {@link ItemRequestUpdatedResponse }
     * {@link ItemRequested }
     * {@link ItemRequestedResponse }
     * {@link ItemShipped }
     * {@link ItemShippedResponse }
     * {@link ItemUpdated }
     * {@link ItemUpdatedResponse }
     * {@link LookupAgency }
     * {@link LookupAgencyResponse }
     * {@link LookupItem }
     * {@link LookupItemResponse }
     * {@link LookupUser }
     * {@link LookupUserResponse }
     * {@link RecallItem }
     * {@link RecallItemResponse }
     * {@link RenewItem }
     * {@link RenewItemResponse }
     * {@link ReportCirculationStatusChange }
     * {@link ReportCirculationStatusChangeResponse }
     * {@link RequestItem }
     * {@link RequestItemResponse }
     * {@link SendUserNotice }
     * {@link SendUserNoticeResponse }
     * {@link UndoCheckOutItem }
     * {@link UndoCheckOutItemResponse }
     * {@link UpdateAgency }
     * {@link UpdateAgencyResponse }
     * {@link UpdateCirculationStatus }
     * {@link UpdateCirculationStatusResponse }
     * {@link UpdateItem }
     * {@link UpdateItemResponse }
     * {@link UpdateRequestItem }
     * {@link UpdateRequestItemResponse }
     * {@link UpdateUser }
     * {@link UpdateUserResponse }
     * {@link UserCreated }
     * {@link UserCreatedResponse }
     * {@link UserFiscalTransactionCreated }
     * {@link UserFiscalTransactionCreatedResponse }
     * {@link UserNoticeSent }
     * {@link UserNoticeSentResponse }
     * {@link UserUpdated }
     * {@link UserUpdatedResponse }
     * 
     * 
     */
    public List<Object> getAcceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse() {
        if (acceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse == null) {
            acceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse = new ArrayList<Object>();
        }
        return this.acceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse;
    }

    // Added by ian to hide the horror of the above from the client class
    public List<Object> getHelper() {
      return this.getAcceptItemOrAcceptItemResponseOrAgencyCreatedOrAgencyCreatedResponseOrAgencyUpdatedOrAgencyUpdatedResponseOrAuthenticateUserOrAuthenticateUserResponseOrCancelRecallItemOrCancelRecallItemResponseOrCancelRequestItemOrCancelRequestItemResponseOrCheckInItemOrCheckInItemResponseOrCheckOutItemOrCheckOutItemResponseOrCirculationStatusChangeReportedOrCirculationStatusChangeReportedResponseOrCirculationStatusUpdatedOrCirculationStatusUpdatedResponseOrCreateAgencyOrCreateAgencyResponseOrCreateItemOrCreateItemResponseOrCreateUserOrCreateUserResponseOrCreateUserFiscalTransactionOrCreateUserFiscalTransactionResponseOrItemCheckedInOrItemCheckedInResponseOrItemCheckedOutOrItemCheckedOutResponseOrItemCreatedOrItemCreatedResponseOrItemRecallCancelledOrItemRecallCancelledResponseOrItemRecalledOrItemRecalledResponseOrItemReceivedOrItemReceivedResponseOrItemRenewedOrItemRenewedResponseOrItemRequestCancelledOrItemRequestCancelledResponseOrItemRequestUpdatedOrItemRequestUpdatedResponseOrItemRequestedOrItemRequestedResponseOrItemShippedOrItemShippedResponseOrItemUpdatedOrItemUpdatedResponseOrLookupAgencyOrLookupAgencyResponseOrLookupItemOrLookupItemResponseOrLookupUserOrLookupUserResponseOrRecallItemOrRecallItemResponseOrRenewItemOrRenewItemResponseOrReportCirculationStatusChangeOrReportCirculationStatusChangeResponseOrRequestItemOrRequestItemResponseOrSendUserNoticeOrSendUserNoticeResponseOrUndoCheckOutItemOrUndoCheckOutItemResponseOrUpdateAgencyOrUpdateAgencyResponseOrUpdateCirculationStatusOrUpdateCirculationStatusResponseOrUpdateItemOrUpdateItemResponseOrUpdateRequestItemOrUpdateRequestItemResponseOrUpdateUserOrUpdateUserResponseOrUserCreatedOrUserCreatedResponseOrUserFiscalTransactionCreatedOrUserFiscalTransactionCreatedResponseOrUserNoticeSentOrUserNoticeSentResponseOrUserUpdatedOrUserUpdatedResponse();
    }
}
