//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.olf.ncip.v1schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.olf.ncip.v1schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthenticationPromptType }
     * 
     */
    public AuthenticationPromptType createAuthenticationPromptType() {
        return new AuthenticationPromptType();
    }

    /**
     * Create an instance of {@link Scheme }
     * 
     */
    public Scheme createScheme() {
        return new Scheme();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link TitleOfComponent }
     * 
     */
    public TitleOfComponent createTitleOfComponent() {
        return new TitleOfComponent();
    }

    /**
     * Create an instance of {@link UpdateAgency }
     * 
     */
    public UpdateAgency createUpdateAgency() {
        return new UpdateAgency();
    }

    /**
     * Create an instance of {@link InitiationHeader }
     * 
     */
    public InitiationHeader createInitiationHeader() {
        return new InitiationHeader();
    }

    /**
     * Create an instance of {@link MandatedAction }
     * 
     */
    public MandatedAction createMandatedAction() {
        return new MandatedAction();
    }

    /**
     * Create an instance of {@link UniqueAgencyId }
     * 
     */
    public UniqueAgencyId createUniqueAgencyId() {
        return new UniqueAgencyId();
    }

    /**
     * Create an instance of {@link DeleteAgencyFields }
     * 
     */
    public DeleteAgencyFields createDeleteAgencyFields() {
        return new DeleteAgencyFields();
    }

    /**
     * Create an instance of {@link AddAgencyFields }
     * 
     */
    public AddAgencyFields createAddAgencyFields() {
        return new AddAgencyFields();
    }

    /**
     * Create an instance of {@link NameInformation }
     * 
     */
    public NameInformation createNameInformation() {
        return new NameInformation();
    }

    /**
     * Create an instance of {@link PersonalNameInformation }
     * 
     */
    public PersonalNameInformation createPersonalNameInformation() {
        return new PersonalNameInformation();
    }

    /**
     * Create an instance of {@link OrganizationNameInformation }
     * 
     */
    public OrganizationNameInformation createOrganizationNameInformation() {
        return new OrganizationNameInformation();
    }

    /**
     * Create an instance of {@link ShippingInformation }
     * 
     */
    public ShippingInformation createShippingInformation() {
        return new ShippingInformation();
    }

    /**
     * Create an instance of {@link ShippingInstructions }
     * 
     */
    public ShippingInstructions createShippingInstructions() {
        return new ShippingInstructions();
    }

    /**
     * Create an instance of {@link ShippingNote }
     * 
     */
    public ShippingNote createShippingNote() {
        return new ShippingNote();
    }

    /**
     * Create an instance of {@link PhysicalAddress }
     * 
     */
    public PhysicalAddress createPhysicalAddress() {
        return new PhysicalAddress();
    }

    /**
     * Create an instance of {@link ElectronicAddress }
     * 
     */
    public ElectronicAddress createElectronicAddress() {
        return new ElectronicAddress();
    }

    /**
     * Create an instance of {@link ItemRequestUpdated }
     * 
     */
    public ItemRequestUpdated createItemRequestUpdated() {
        return new ItemRequestUpdated();
    }

    /**
     * Create an instance of {@link UniqueUserId }
     * 
     */
    public UniqueUserId createUniqueUserId() {
        return new UniqueUserId();
    }

    /**
     * Create an instance of {@link UniqueItemId }
     * 
     */
    public UniqueItemId createUniqueItemId() {
        return new UniqueItemId();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link UniqueRequestId }
     * 
     */
    public UniqueRequestId createUniqueRequestId() {
        return new UniqueRequestId();
    }

    /**
     * Create an instance of {@link DeleteRequestFields }
     * 
     */
    public DeleteRequestFields createDeleteRequestFields() {
        return new DeleteRequestFields();
    }

    /**
     * Create an instance of {@link AddRequestFields }
     * 
     */
    public AddRequestFields createAddRequestFields() {
        return new AddRequestFields();
    }

    /**
     * Create an instance of {@link ItemOptionalFields }
     * 
     */
    public ItemOptionalFields createItemOptionalFields() {
        return new ItemOptionalFields();
    }

    /**
     * Create an instance of {@link UserOptionalFields }
     * 
     */
    public UserOptionalFields createUserOptionalFields() {
        return new UserOptionalFields();
    }

    /**
     * Create an instance of {@link DateReceived }
     * 
     */
    public DateReceived createDateReceived() {
        return new DateReceived();
    }

    /**
     * Create an instance of {@link RelatedFiscalTransactionReferenceId }
     * 
     */
    public RelatedFiscalTransactionReferenceId createRelatedFiscalTransactionReferenceId() {
        return new RelatedFiscalTransactionReferenceId();
    }

    /**
     * Create an instance of {@link FiscalTransactionIdentifierValue }
     * 
     */
    public FiscalTransactionIdentifierValue createFiscalTransactionIdentifierValue() {
        return new FiscalTransactionIdentifierValue();
    }

    /**
     * Create an instance of {@link LocationNameLevel }
     * 
     */
    public LocationNameLevel createLocationNameLevel() {
        return new LocationNameLevel();
    }

    /**
     * Create an instance of {@link ToSystemId }
     * 
     */
    public ToSystemId createToSystemId() {
        return new ToSystemId();
    }

    /**
     * Create an instance of {@link CurrencyCode }
     * 
     */
    public CurrencyCode createCurrencyCode() {
        return new CurrencyCode();
    }

    /**
     * Create an instance of {@link DateReturned }
     * 
     */
    public DateReturned createDateReturned() {
        return new DateReturned();
    }

    /**
     * Create an instance of {@link AuthenticationDataFormatType }
     * 
     */
    public AuthenticationDataFormatType createAuthenticationDataFormatType() {
        return new AuthenticationDataFormatType();
    }

    /**
     * Create an instance of {@link PlaceOfPublication }
     * 
     */
    public PlaceOfPublication createPlaceOfPublication() {
        return new PlaceOfPublication();
    }

    /**
     * Create an instance of {@link HoldingsEnumeration }
     * 
     */
    public HoldingsEnumeration createHoldingsEnumeration() {
        return new HoldingsEnumeration();
    }

    /**
     * Create an instance of {@link EnumerationLevelInstance }
     * 
     */
    public EnumerationLevelInstance createEnumerationLevelInstance() {
        return new EnumerationLevelInstance();
    }

    /**
     * Create an instance of {@link PhysicalConditionDetails }
     * 
     */
    public PhysicalConditionDetails createPhysicalConditionDetails() {
        return new PhysicalConditionDetails();
    }

    /**
     * Create an instance of {@link ElementName }
     * 
     */
    public ElementName createElementName() {
        return new ElementName();
    }

    /**
     * Create an instance of {@link AgencyElementType }
     * 
     */
    public AgencyElementType createAgencyElementType() {
        return new AgencyElementType();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link Problem }
     * 
     */
    public Problem createProblem() {
        return new Problem();
    }

    /**
     * Create an instance of {@link Street }
     * 
     */
    public Street createStreet() {
        return new Street();
    }

    /**
     * Create an instance of {@link CreateItemResponse }
     * 
     */
    public CreateItemResponse createCreateItemResponse() {
        return new CreateItemResponse();
    }

    /**
     * Create an instance of {@link RenewItemResponse }
     * 
     */
    public RenewItemResponse createRenewItemResponse() {
        return new RenewItemResponse();
    }

    /**
     * Create an instance of {@link RequiredFeeAmount }
     * 
     */
    public RequiredFeeAmount createRequiredFeeAmount() {
        return new RequiredFeeAmount();
    }

    /**
     * Create an instance of {@link RequiredItemUseRestrictionType }
     * 
     */
    public RequiredItemUseRestrictionType createRequiredItemUseRestrictionType() {
        return new RequiredItemUseRestrictionType();
    }

    /**
     * Create an instance of {@link Pending }
     * 
     */
    public Pending createPending() {
        return new Pending();
    }

    /**
     * Create an instance of {@link DateDue }
     * 
     */
    public DateDue createDateDue() {
        return new DateDue();
    }

    /**
     * Create an instance of {@link DateForReturn }
     * 
     */
    public DateForReturn createDateForReturn() {
        return new DateForReturn();
    }

    /**
     * Create an instance of {@link RenewalCount }
     * 
     */
    public RenewalCount createRenewalCount() {
        return new RenewalCount();
    }

    /**
     * Create an instance of {@link FiscalTransactionInformation }
     * 
     */
    public FiscalTransactionInformation createFiscalTransactionInformation() {
        return new FiscalTransactionInformation();
    }

    /**
     * Create an instance of {@link BibliographicRecordIdentifier }
     * 
     */
    public BibliographicRecordIdentifier createBibliographicRecordIdentifier() {
        return new BibliographicRecordIdentifier();
    }

    /**
     * Create an instance of {@link SensitizationFlag }
     * 
     */
    public SensitizationFlag createSensitizationFlag() {
        return new SensitizationFlag();
    }

    /**
     * Create an instance of {@link CurrentRequestersDesired }
     * 
     */
    public CurrentRequestersDesired createCurrentRequestersDesired() {
        return new CurrentRequestersDesired();
    }

    /**
     * Create an instance of {@link DateWillSend }
     * 
     */
    public DateWillSend createDateWillSend() {
        return new DateWillSend();
    }

    /**
     * Create an instance of {@link DateShipped }
     * 
     */
    public DateShipped createDateShipped() {
        return new DateShipped();
    }

    /**
     * Create an instance of {@link FromSystemId }
     * 
     */
    public FromSystemId createFromSystemId() {
        return new FromSystemId();
    }

    /**
     * Create an instance of {@link FromSystemAuthentication }
     * 
     */
    public FromSystemAuthentication createFromSystemAuthentication() {
        return new FromSystemAuthentication();
    }

    /**
     * Create an instance of {@link FromAgencyId }
     * 
     */
    public FromAgencyId createFromAgencyId() {
        return new FromAgencyId();
    }

    /**
     * Create an instance of {@link FromAgencyAuthentication }
     * 
     */
    public FromAgencyAuthentication createFromAgencyAuthentication() {
        return new FromAgencyAuthentication();
    }

    /**
     * Create an instance of {@link ToAgencyId }
     * 
     */
    public ToAgencyId createToAgencyId() {
        return new ToAgencyId();
    }

    /**
     * Create an instance of {@link CirculationStatus }
     * 
     */
    public CirculationStatus createCirculationStatus() {
        return new CirculationStatus();
    }

    /**
     * Create an instance of {@link CreateItem }
     * 
     */
    public CreateItem createCreateItem() {
        return new CreateItem();
    }

    /**
     * Create an instance of {@link BibliographicDescription }
     * 
     */
    public BibliographicDescription createBibliographicDescription() {
        return new BibliographicDescription();
    }

    /**
     * Create an instance of {@link ItemUseRestrictionType }
     * 
     */
    public ItemUseRestrictionType createItemUseRestrictionType() {
        return new ItemUseRestrictionType();
    }

    /**
     * Create an instance of {@link ItemDescription }
     * 
     */
    public ItemDescription createItemDescription() {
        return new ItemDescription();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link PhysicalCondition }
     * 
     */
    public PhysicalCondition createPhysicalCondition() {
        return new PhysicalCondition();
    }

    /**
     * Create an instance of {@link SecurityMarker }
     * 
     */
    public SecurityMarker createSecurityMarker() {
        return new SecurityMarker();
    }

    /**
     * Create an instance of {@link NCIPMessage }
     * 
     */
    public NCIPMessage createNCIPMessage() {
        return new NCIPMessage();
    }

    /**
     * Create an instance of {@link AcceptItem }
     * 
     */
    public AcceptItem createAcceptItem() {
        return new AcceptItem();
    }

    /**
     * Create an instance of {@link AcceptItemResponse }
     * 
     */
    public AcceptItemResponse createAcceptItemResponse() {
        return new AcceptItemResponse();
    }

    /**
     * Create an instance of {@link AgencyCreated }
     * 
     */
    public AgencyCreated createAgencyCreated() {
        return new AgencyCreated();
    }

    /**
     * Create an instance of {@link AgencyCreatedResponse }
     * 
     */
    public AgencyCreatedResponse createAgencyCreatedResponse() {
        return new AgencyCreatedResponse();
    }

    /**
     * Create an instance of {@link AgencyUpdated }
     * 
     */
    public AgencyUpdated createAgencyUpdated() {
        return new AgencyUpdated();
    }

    /**
     * Create an instance of {@link AgencyUpdatedResponse }
     * 
     */
    public AgencyUpdatedResponse createAgencyUpdatedResponse() {
        return new AgencyUpdatedResponse();
    }

    /**
     * Create an instance of {@link AuthenticateUser }
     * 
     */
    public AuthenticateUser createAuthenticateUser() {
        return new AuthenticateUser();
    }

    /**
     * Create an instance of {@link AuthenticateUserResponse }
     * 
     */
    public AuthenticateUserResponse createAuthenticateUserResponse() {
        return new AuthenticateUserResponse();
    }

    /**
     * Create an instance of {@link CancelRecallItem }
     * 
     */
    public CancelRecallItem createCancelRecallItem() {
        return new CancelRecallItem();
    }

    /**
     * Create an instance of {@link CancelRecallItemResponse }
     * 
     */
    public CancelRecallItemResponse createCancelRecallItemResponse() {
        return new CancelRecallItemResponse();
    }

    /**
     * Create an instance of {@link CancelRequestItem }
     * 
     */
    public CancelRequestItem createCancelRequestItem() {
        return new CancelRequestItem();
    }

    /**
     * Create an instance of {@link CancelRequestItemResponse }
     * 
     */
    public CancelRequestItemResponse createCancelRequestItemResponse() {
        return new CancelRequestItemResponse();
    }

    /**
     * Create an instance of {@link CheckInItem }
     * 
     */
    public CheckInItem createCheckInItem() {
        return new CheckInItem();
    }

    /**
     * Create an instance of {@link CheckInItemResponse }
     * 
     */
    public CheckInItemResponse createCheckInItemResponse() {
        return new CheckInItemResponse();
    }

    /**
     * Create an instance of {@link CheckOutItem }
     * 
     */
    public CheckOutItem createCheckOutItem() {
        return new CheckOutItem();
    }

    /**
     * Create an instance of {@link CheckOutItemResponse }
     * 
     */
    public CheckOutItemResponse createCheckOutItemResponse() {
        return new CheckOutItemResponse();
    }

    /**
     * Create an instance of {@link CirculationStatusChangeReported }
     * 
     */
    public CirculationStatusChangeReported createCirculationStatusChangeReported() {
        return new CirculationStatusChangeReported();
    }

    /**
     * Create an instance of {@link CirculationStatusChangeReportedResponse }
     * 
     */
    public CirculationStatusChangeReportedResponse createCirculationStatusChangeReportedResponse() {
        return new CirculationStatusChangeReportedResponse();
    }

    /**
     * Create an instance of {@link CirculationStatusUpdated }
     * 
     */
    public CirculationStatusUpdated createCirculationStatusUpdated() {
        return new CirculationStatusUpdated();
    }

    /**
     * Create an instance of {@link CirculationStatusUpdatedResponse }
     * 
     */
    public CirculationStatusUpdatedResponse createCirculationStatusUpdatedResponse() {
        return new CirculationStatusUpdatedResponse();
    }

    /**
     * Create an instance of {@link CreateAgency }
     * 
     */
    public CreateAgency createCreateAgency() {
        return new CreateAgency();
    }

    /**
     * Create an instance of {@link CreateAgencyResponse }
     * 
     */
    public CreateAgencyResponse createCreateAgencyResponse() {
        return new CreateAgencyResponse();
    }

    /**
     * Create an instance of {@link CreateUser }
     * 
     */
    public CreateUser createCreateUser() {
        return new CreateUser();
    }

    /**
     * Create an instance of {@link CreateUserFiscalTransaction }
     * 
     */
    public CreateUserFiscalTransaction createCreateUserFiscalTransaction() {
        return new CreateUserFiscalTransaction();
    }

    /**
     * Create an instance of {@link CreateUserFiscalTransactionResponse }
     * 
     */
    public CreateUserFiscalTransactionResponse createCreateUserFiscalTransactionResponse() {
        return new CreateUserFiscalTransactionResponse();
    }

    /**
     * Create an instance of {@link ItemCheckedIn }
     * 
     */
    public ItemCheckedIn createItemCheckedIn() {
        return new ItemCheckedIn();
    }

    /**
     * Create an instance of {@link ItemCheckedInResponse }
     * 
     */
    public ItemCheckedInResponse createItemCheckedInResponse() {
        return new ItemCheckedInResponse();
    }

    /**
     * Create an instance of {@link ItemCheckedOut }
     * 
     */
    public ItemCheckedOut createItemCheckedOut() {
        return new ItemCheckedOut();
    }

    /**
     * Create an instance of {@link ItemCheckedOutResponse }
     * 
     */
    public ItemCheckedOutResponse createItemCheckedOutResponse() {
        return new ItemCheckedOutResponse();
    }

    /**
     * Create an instance of {@link ItemCreated }
     * 
     */
    public ItemCreated createItemCreated() {
        return new ItemCreated();
    }

    /**
     * Create an instance of {@link ItemCreatedResponse }
     * 
     */
    public ItemCreatedResponse createItemCreatedResponse() {
        return new ItemCreatedResponse();
    }

    /**
     * Create an instance of {@link ItemRecallCancelled }
     * 
     */
    public ItemRecallCancelled createItemRecallCancelled() {
        return new ItemRecallCancelled();
    }

    /**
     * Create an instance of {@link ItemRecallCancelledResponse }
     * 
     */
    public ItemRecallCancelledResponse createItemRecallCancelledResponse() {
        return new ItemRecallCancelledResponse();
    }

    /**
     * Create an instance of {@link ItemRecalled }
     * 
     */
    public ItemRecalled createItemRecalled() {
        return new ItemRecalled();
    }

    /**
     * Create an instance of {@link ItemRecalledResponse }
     * 
     */
    public ItemRecalledResponse createItemRecalledResponse() {
        return new ItemRecalledResponse();
    }

    /**
     * Create an instance of {@link ItemReceived }
     * 
     */
    public ItemReceived createItemReceived() {
        return new ItemReceived();
    }

    /**
     * Create an instance of {@link ItemReceivedResponse }
     * 
     */
    public ItemReceivedResponse createItemReceivedResponse() {
        return new ItemReceivedResponse();
    }

    /**
     * Create an instance of {@link ItemRenewed }
     * 
     */
    public ItemRenewed createItemRenewed() {
        return new ItemRenewed();
    }

    /**
     * Create an instance of {@link ItemRenewedResponse }
     * 
     */
    public ItemRenewedResponse createItemRenewedResponse() {
        return new ItemRenewedResponse();
    }

    /**
     * Create an instance of {@link ItemRequestCancelled }
     * 
     */
    public ItemRequestCancelled createItemRequestCancelled() {
        return new ItemRequestCancelled();
    }

    /**
     * Create an instance of {@link ItemRequestCancelledResponse }
     * 
     */
    public ItemRequestCancelledResponse createItemRequestCancelledResponse() {
        return new ItemRequestCancelledResponse();
    }

    /**
     * Create an instance of {@link ItemRequestUpdatedResponse }
     * 
     */
    public ItemRequestUpdatedResponse createItemRequestUpdatedResponse() {
        return new ItemRequestUpdatedResponse();
    }

    /**
     * Create an instance of {@link ItemRequested }
     * 
     */
    public ItemRequested createItemRequested() {
        return new ItemRequested();
    }

    /**
     * Create an instance of {@link ItemRequestedResponse }
     * 
     */
    public ItemRequestedResponse createItemRequestedResponse() {
        return new ItemRequestedResponse();
    }

    /**
     * Create an instance of {@link ItemShipped }
     * 
     */
    public ItemShipped createItemShipped() {
        return new ItemShipped();
    }

    /**
     * Create an instance of {@link ItemShippedResponse }
     * 
     */
    public ItemShippedResponse createItemShippedResponse() {
        return new ItemShippedResponse();
    }

    /**
     * Create an instance of {@link ItemUpdated }
     * 
     */
    public ItemUpdated createItemUpdated() {
        return new ItemUpdated();
    }

    /**
     * Create an instance of {@link ItemUpdatedResponse }
     * 
     */
    public ItemUpdatedResponse createItemUpdatedResponse() {
        return new ItemUpdatedResponse();
    }

    /**
     * Create an instance of {@link LookupAgency }
     * 
     */
    public LookupAgency createLookupAgency() {
        return new LookupAgency();
    }

    /**
     * Create an instance of {@link LookupAgencyResponse }
     * 
     */
    public LookupAgencyResponse createLookupAgencyResponse() {
        return new LookupAgencyResponse();
    }

    /**
     * Create an instance of {@link LookupItem }
     * 
     */
    public LookupItem createLookupItem() {
        return new LookupItem();
    }

    /**
     * Create an instance of {@link LookupItemResponse }
     * 
     */
    public LookupItemResponse createLookupItemResponse() {
        return new LookupItemResponse();
    }

    /**
     * Create an instance of {@link LookupUser }
     * 
     */
    public LookupUser createLookupUser() {
        return new LookupUser();
    }

    /**
     * Create an instance of {@link LookupUserResponse }
     * 
     */
    public LookupUserResponse createLookupUserResponse() {
        return new LookupUserResponse();
    }

    /**
     * Create an instance of {@link RecallItem }
     * 
     */
    public RecallItem createRecallItem() {
        return new RecallItem();
    }

    /**
     * Create an instance of {@link RecallItemResponse }
     * 
     */
    public RecallItemResponse createRecallItemResponse() {
        return new RecallItemResponse();
    }

    /**
     * Create an instance of {@link RenewItem }
     * 
     */
    public RenewItem createRenewItem() {
        return new RenewItem();
    }

    /**
     * Create an instance of {@link ReportCirculationStatusChange }
     * 
     */
    public ReportCirculationStatusChange createReportCirculationStatusChange() {
        return new ReportCirculationStatusChange();
    }

    /**
     * Create an instance of {@link ReportCirculationStatusChangeResponse }
     * 
     */
    public ReportCirculationStatusChangeResponse createReportCirculationStatusChangeResponse() {
        return new ReportCirculationStatusChangeResponse();
    }

    /**
     * Create an instance of {@link RequestItem }
     * 
     */
    public RequestItem createRequestItem() {
        return new RequestItem();
    }

    /**
     * Create an instance of {@link RequestItemResponse }
     * 
     */
    public RequestItemResponse createRequestItemResponse() {
        return new RequestItemResponse();
    }

    /**
     * Create an instance of {@link SendUserNotice }
     * 
     */
    public SendUserNotice createSendUserNotice() {
        return new SendUserNotice();
    }

    /**
     * Create an instance of {@link SendUserNoticeResponse }
     * 
     */
    public SendUserNoticeResponse createSendUserNoticeResponse() {
        return new SendUserNoticeResponse();
    }

    /**
     * Create an instance of {@link UndoCheckOutItem }
     * 
     */
    public UndoCheckOutItem createUndoCheckOutItem() {
        return new UndoCheckOutItem();
    }

    /**
     * Create an instance of {@link UndoCheckOutItemResponse }
     * 
     */
    public UndoCheckOutItemResponse createUndoCheckOutItemResponse() {
        return new UndoCheckOutItemResponse();
    }

    /**
     * Create an instance of {@link UpdateAgencyResponse }
     * 
     */
    public UpdateAgencyResponse createUpdateAgencyResponse() {
        return new UpdateAgencyResponse();
    }

    /**
     * Create an instance of {@link UpdateCirculationStatus }
     * 
     */
    public UpdateCirculationStatus createUpdateCirculationStatus() {
        return new UpdateCirculationStatus();
    }

    /**
     * Create an instance of {@link UpdateCirculationStatusResponse }
     * 
     */
    public UpdateCirculationStatusResponse createUpdateCirculationStatusResponse() {
        return new UpdateCirculationStatusResponse();
    }

    /**
     * Create an instance of {@link UpdateItem }
     * 
     */
    public UpdateItem createUpdateItem() {
        return new UpdateItem();
    }

    /**
     * Create an instance of {@link UpdateItemResponse }
     * 
     */
    public UpdateItemResponse createUpdateItemResponse() {
        return new UpdateItemResponse();
    }

    /**
     * Create an instance of {@link UpdateRequestItem }
     * 
     */
    public UpdateRequestItem createUpdateRequestItem() {
        return new UpdateRequestItem();
    }

    /**
     * Create an instance of {@link UpdateRequestItemResponse }
     * 
     */
    public UpdateRequestItemResponse createUpdateRequestItemResponse() {
        return new UpdateRequestItemResponse();
    }

    /**
     * Create an instance of {@link UpdateUser }
     * 
     */
    public UpdateUser createUpdateUser() {
        return new UpdateUser();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link UserCreated }
     * 
     */
    public UserCreated createUserCreated() {
        return new UserCreated();
    }

    /**
     * Create an instance of {@link UserCreatedResponse }
     * 
     */
    public UserCreatedResponse createUserCreatedResponse() {
        return new UserCreatedResponse();
    }

    /**
     * Create an instance of {@link UserFiscalTransactionCreated }
     * 
     */
    public UserFiscalTransactionCreated createUserFiscalTransactionCreated() {
        return new UserFiscalTransactionCreated();
    }

    /**
     * Create an instance of {@link UserFiscalTransactionCreatedResponse }
     * 
     */
    public UserFiscalTransactionCreatedResponse createUserFiscalTransactionCreatedResponse() {
        return new UserFiscalTransactionCreatedResponse();
    }

    /**
     * Create an instance of {@link UserNoticeSent }
     * 
     */
    public UserNoticeSent createUserNoticeSent() {
        return new UserNoticeSent();
    }

    /**
     * Create an instance of {@link UserNoticeSentResponse }
     * 
     */
    public UserNoticeSentResponse createUserNoticeSentResponse() {
        return new UserNoticeSentResponse();
    }

    /**
     * Create an instance of {@link UserUpdated }
     * 
     */
    public UserUpdated createUserUpdated() {
        return new UserUpdated();
    }

    /**
     * Create an instance of {@link UserUpdatedResponse }
     * 
     */
    public UserUpdatedResponse createUserUpdatedResponse() {
        return new UserUpdatedResponse();
    }

    /**
     * Create an instance of {@link ItemIdentifierValue }
     * 
     */
    public ItemIdentifierValue createItemIdentifierValue() {
        return new ItemIdentifierValue();
    }

    /**
     * Create an instance of {@link StructuredAddress }
     * 
     */
    public StructuredAddress createStructuredAddress() {
        return new StructuredAddress();
    }

    /**
     * Create an instance of {@link LocationWithinBuilding }
     * 
     */
    public LocationWithinBuilding createLocationWithinBuilding() {
        return new LocationWithinBuilding();
    }

    /**
     * Create an instance of {@link HouseName }
     * 
     */
    public HouseName createHouseName() {
        return new HouseName();
    }

    /**
     * Create an instance of {@link District }
     * 
     */
    public District createDistrict() {
        return new District();
    }

    /**
     * Create an instance of {@link PostOfficeBox }
     * 
     */
    public PostOfficeBox createPostOfficeBox() {
        return new PostOfficeBox();
    }

    /**
     * Create an instance of {@link Line1 }
     * 
     */
    public Line1 createLine1() {
        return new Line1();
    }

    /**
     * Create an instance of {@link Line2 }
     * 
     */
    public Line2 createLine2() {
        return new Line2();
    }

    /**
     * Create an instance of {@link Locality }
     * 
     */
    public Locality createLocality() {
        return new Locality();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link PostalCode }
     * 
     */
    public PostalCode createPostalCode() {
        return new PostalCode();
    }

    /**
     * Create an instance of {@link CareOf }
     * 
     */
    public CareOf createCareOf() {
        return new CareOf();
    }

    /**
     * Create an instance of {@link Initials }
     * 
     */
    public Initials createInitials() {
        return new Initials();
    }

    /**
     * Create an instance of {@link UnstructuredPersonalUserName }
     * 
     */
    public UnstructuredPersonalUserName createUnstructuredPersonalUserName() {
        return new UnstructuredPersonalUserName();
    }

    /**
     * Create an instance of {@link StructuredPersonalUserName }
     * 
     */
    public StructuredPersonalUserName createStructuredPersonalUserName() {
        return new StructuredPersonalUserName();
    }

    /**
     * Create an instance of {@link DesiredDateForReturn }
     * 
     */
    public DesiredDateForReturn createDesiredDateForReturn() {
        return new DesiredDateForReturn();
    }

    /**
     * Create an instance of {@link UnstructuredAddressData }
     * 
     */
    public UnstructuredAddressData createUnstructuredAddressData() {
        return new UnstructuredAddressData();
    }

    /**
     * Create an instance of {@link AuthorOfComponent }
     * 
     */
    public AuthorOfComponent createAuthorOfComponent() {
        return new AuthorOfComponent();
    }

    /**
     * Create an instance of {@link BibliographicItemIdentifier }
     * 
     */
    public BibliographicItemIdentifier createBibliographicItemIdentifier() {
        return new BibliographicItemIdentifier();
    }

    /**
     * Create an instance of {@link DateSent }
     * 
     */
    public DateSent createDateSent() {
        return new DateSent();
    }

    /**
     * Create an instance of {@link HoldPickupDate }
     * 
     */
    public HoldPickupDate createHoldPickupDate() {
        return new HoldPickupDate();
    }

    /**
     * Create an instance of {@link EnumerationCaption }
     * 
     */
    public EnumerationCaption createEnumerationCaption() {
        return new EnumerationCaption();
    }

    /**
     * Create an instance of {@link EnumerationLevel }
     * 
     */
    public EnumerationLevel createEnumerationLevel() {
        return new EnumerationLevel();
    }

    /**
     * Create an instance of {@link EnumerationValue }
     * 
     */
    public EnumerationValue createEnumerationValue() {
        return new EnumerationValue();
    }

    /**
     * Create an instance of {@link UnstructuredHoldingsData }
     * 
     */
    public UnstructuredHoldingsData createUnstructuredHoldingsData() {
        return new UnstructuredHoldingsData();
    }

    /**
     * Create an instance of {@link CurrentBorrower }
     * 
     */
    public CurrentBorrower createCurrentBorrower() {
        return new CurrentBorrower();
    }

    /**
     * Create an instance of {@link AddItemFields }
     * 
     */
    public AddItemFields createAddItemFields() {
        return new AddItemFields();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link NeedBeforeDate }
     * 
     */
    public NeedBeforeDate createNeedBeforeDate() {
        return new NeedBeforeDate();
    }

    /**
     * Create an instance of {@link BibliographicItemIdentifierCode }
     * 
     */
    public BibliographicItemIdentifierCode createBibliographicItemIdentifierCode() {
        return new BibliographicItemIdentifierCode();
    }

    /**
     * Create an instance of {@link Prefix }
     * 
     */
    public Prefix createPrefix() {
        return new Prefix();
    }

    /**
     * Create an instance of {@link MessagingError }
     * 
     */
    public MessagingError createMessagingError() {
        return new MessagingError();
    }

    /**
     * Create an instance of {@link LocationName }
     * 
     */
    public LocationName createLocationName() {
        return new LocationName();
    }

    /**
     * Create an instance of {@link LocationNameInstance }
     * 
     */
    public LocationNameInstance createLocationNameInstance() {
        return new LocationNameInstance();
    }

    /**
     * Create an instance of {@link RoutingInformation }
     * 
     */
    public RoutingInformation createRoutingInformation() {
        return new RoutingInformation();
    }

    /**
     * Create an instance of {@link RoutingInstructions }
     * 
     */
    public RoutingInstructions createRoutingInstructions() {
        return new RoutingInstructions();
    }

    /**
     * Create an instance of {@link Destination }
     * 
     */
    public Destination createDestination() {
        return new Destination();
    }

    /**
     * Create an instance of {@link DeleteItemFields }
     * 
     */
    public DeleteItemFields createDeleteItemFields() {
        return new DeleteItemFields();
    }

    /**
     * Create an instance of {@link HoldQueueLength }
     * 
     */
    public HoldQueueLength createHoldQueueLength() {
        return new HoldQueueLength();
    }

    /**
     * Create an instance of {@link CallNumber }
     * 
     */
    public CallNumber createCallNumber() {
        return new CallNumber();
    }

    /**
     * Create an instance of {@link ChronologyLevelInstance }
     * 
     */
    public ChronologyLevelInstance createChronologyLevelInstance() {
        return new ChronologyLevelInstance();
    }

    /**
     * Create an instance of {@link ChronologyCaption }
     * 
     */
    public ChronologyCaption createChronologyCaption() {
        return new ChronologyCaption();
    }

    /**
     * Create an instance of {@link ChronologyLevel }
     * 
     */
    public ChronologyLevel createChronologyLevel() {
        return new ChronologyLevel();
    }

    /**
     * Create an instance of {@link ChronologyValue }
     * 
     */
    public ChronologyValue createChronologyValue() {
        return new ChronologyValue();
    }

    /**
     * Create an instance of {@link ElectronicResource }
     * 
     */
    public ElectronicResource createElectronicResource() {
        return new ElectronicResource();
    }

    /**
     * Create an instance of {@link ElectronicDataFormatType }
     * 
     */
    public ElectronicDataFormatType createElectronicDataFormatType() {
        return new ElectronicDataFormatType();
    }

    /**
     * Create an instance of {@link ActualResource }
     * 
     */
    public ActualResource createActualResource() {
        return new ActualResource();
    }

    /**
     * Create an instance of {@link ReferenceToResource }
     * 
     */
    public ReferenceToResource createReferenceToResource() {
        return new ReferenceToResource();
    }

    /**
     * Create an instance of {@link MonetaryValue }
     * 
     */
    public MonetaryValue createMonetaryValue() {
        return new MonetaryValue();
    }

    /**
     * Create an instance of {@link ElectronicAddressType }
     * 
     */
    public ElectronicAddressType createElectronicAddressType() {
        return new ElectronicAddressType();
    }

    /**
     * Create an instance of {@link ElectronicAddressData }
     * 
     */
    public ElectronicAddressData createElectronicAddressData() {
        return new ElectronicAddressData();
    }

    /**
     * Create an instance of {@link UserFiscalAccount }
     * 
     */
    public UserFiscalAccount createUserFiscalAccount() {
        return new UserFiscalAccount();
    }

    /**
     * Create an instance of {@link AccountBalance }
     * 
     */
    public AccountBalance createAccountBalance() {
        return new AccountBalance();
    }

    /**
     * Create an instance of {@link AccountDetails }
     * 
     */
    public AccountDetails createAccountDetails() {
        return new AccountDetails();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link BibliographicItemId }
     * 
     */
    public BibliographicItemId createBibliographicItemId() {
        return new BibliographicItemId();
    }

    /**
     * Create an instance of {@link ProcessingErrorType }
     * 
     */
    public ProcessingErrorType createProcessingErrorType() {
        return new ProcessingErrorType();
    }

    /**
     * Create an instance of {@link DateReportedReturned }
     * 
     */
    public DateReportedReturned createDateReportedReturned() {
        return new DateReportedReturned();
    }

    /**
     * Create an instance of {@link ComponentId }
     * 
     */
    public ComponentId createComponentId() {
        return new ComponentId();
    }

    /**
     * Create an instance of {@link ComponentIdentifierType }
     * 
     */
    public ComponentIdentifierType createComponentIdentifierType() {
        return new ComponentIdentifierType();
    }

    /**
     * Create an instance of {@link ComponentIdentifier }
     * 
     */
    public ComponentIdentifier createComponentIdentifier() {
        return new ComponentIdentifier();
    }

    /**
     * Create an instance of {@link Surname }
     * 
     */
    public Surname createSurname() {
        return new Surname();
    }

    /**
     * Create an instance of {@link PublicationDateOfComponent }
     * 
     */
    public PublicationDateOfComponent createPublicationDateOfComponent() {
        return new PublicationDateOfComponent();
    }

    /**
     * Create an instance of {@link ProcessingErrorElement }
     * 
     */
    public ProcessingErrorElement createProcessingErrorElement() {
        return new ProcessingErrorElement();
    }

    /**
     * Create an instance of {@link ProcessingErrorValue }
     * 
     */
    public ProcessingErrorValue createProcessingErrorValue() {
        return new ProcessingErrorValue();
    }

    /**
     * Create an instance of {@link RequestedItem }
     * 
     */
    public RequestedItem createRequestedItem() {
        return new RequestedItem();
    }

    /**
     * Create an instance of {@link RequestStatusType }
     * 
     */
    public RequestStatusType createRequestStatusType() {
        return new RequestStatusType();
    }

    /**
     * Create an instance of {@link DatePlaced }
     * 
     */
    public DatePlaced createDatePlaced() {
        return new DatePlaced();
    }

    /**
     * Create an instance of {@link PickupDate }
     * 
     */
    public PickupDate createPickupDate() {
        return new PickupDate();
    }

    /**
     * Create an instance of {@link PickupExpiryDate }
     * 
     */
    public PickupExpiryDate createPickupExpiryDate() {
        return new PickupExpiryDate();
    }

    /**
     * Create an instance of {@link ReminderLevel }
     * 
     */
    public ReminderLevel createReminderLevel() {
        return new ReminderLevel();
    }

    /**
     * Create an instance of {@link HoldQueuePosition }
     * 
     */
    public HoldQueuePosition createHoldQueuePosition() {
        return new HoldQueuePosition();
    }

    /**
     * Create an instance of {@link AuthenticationPromptData }
     * 
     */
    public AuthenticationPromptData createAuthenticationPromptData() {
        return new AuthenticationPromptData();
    }

    /**
     * Create an instance of {@link GivenName }
     * 
     */
    public GivenName createGivenName() {
        return new GivenName();
    }

    /**
     * Create an instance of {@link LocationNameValue }
     * 
     */
    public LocationNameValue createLocationNameValue() {
        return new LocationNameValue();
    }

    /**
     * Create an instance of {@link OnBehalfOfAgency }
     * 
     */
    public OnBehalfOfAgency createOnBehalfOfAgency() {
        return new OnBehalfOfAgency();
    }

    /**
     * Create an instance of {@link RequestIdentifierValue }
     * 
     */
    public RequestIdentifierValue createRequestIdentifierValue() {
        return new RequestIdentifierValue();
    }

    /**
     * Create an instance of {@link StructuredHoldingsData }
     * 
     */
    public StructuredHoldingsData createStructuredHoldingsData() {
        return new StructuredHoldingsData();
    }

    /**
     * Create an instance of {@link HoldingsChronology }
     * 
     */
    public HoldingsChronology createHoldingsChronology() {
        return new HoldingsChronology();
    }

    /**
     * Create an instance of {@link RequestScopeType }
     * 
     */
    public RequestScopeType createRequestScopeType() {
        return new RequestScopeType();
    }

    /**
     * Create an instance of {@link AuthenticationInput }
     * 
     */
    public AuthenticationInput createAuthenticationInput() {
        return new AuthenticationInput();
    }

    /**
     * Create an instance of {@link ItemElementType }
     * 
     */
    public ItemElementType createItemElementType() {
        return new ItemElementType();
    }

    /**
     * Create an instance of {@link UserElementType }
     * 
     */
    public UserElementType createUserElementType() {
        return new UserElementType();
    }

    /**
     * Create an instance of {@link DesiredDateDue }
     * 
     */
    public DesiredDateDue createDesiredDateDue() {
        return new DesiredDateDue();
    }

    /**
     * Create an instance of {@link AcknowledgedFeeAmount }
     * 
     */
    public AcknowledgedFeeAmount createAcknowledgedFeeAmount() {
        return new AcknowledgedFeeAmount();
    }

    /**
     * Create an instance of {@link AcknowledgedItemUseRestrictionType }
     * 
     */
    public AcknowledgedItemUseRestrictionType createAcknowledgedItemUseRestrictionType() {
        return new AcknowledgedItemUseRestrictionType();
    }

    /**
     * Create an instance of {@link AccrualDate }
     * 
     */
    public AccrualDate createAccrualDate() {
        return new AccrualDate();
    }

    /**
     * Create an instance of {@link PaymentMethodType }
     * 
     */
    public PaymentMethodType createPaymentMethodType() {
        return new PaymentMethodType();
    }

    /**
     * Create an instance of {@link MessagingErrorElement }
     * 
     */
    public MessagingErrorElement createMessagingErrorElement() {
        return new MessagingErrorElement();
    }

    /**
     * Create an instance of {@link MessagingErrorValue }
     * 
     */
    public MessagingErrorValue createMessagingErrorValue() {
        return new MessagingErrorValue();
    }

    /**
     * Create an instance of {@link EarliestDateNeeded }
     * 
     */
    public EarliestDateNeeded createEarliestDateNeeded() {
        return new EarliestDateNeeded();
    }

    /**
     * Create an instance of {@link BibliographicRecordIdentifierCode }
     * 
     */
    public BibliographicRecordIdentifierCode createBibliographicRecordIdentifierCode() {
        return new BibliographicRecordIdentifierCode();
    }

    /**
     * Create an instance of {@link LoanedItemsCount }
     * 
     */
    public LoanedItemsCount createLoanedItemsCount() {
        return new LoanedItemsCount();
    }

    /**
     * Create an instance of {@link RequestedItemsCount }
     * 
     */
    public RequestedItemsCount createRequestedItemsCount() {
        return new RequestedItemsCount();
    }

    /**
     * Create an instance of {@link UserTransaction }
     * 
     */
    public UserTransaction createUserTransaction() {
        return new UserTransaction();
    }

    /**
     * Create an instance of {@link RenewalNotPermitted }
     * 
     */
    public RenewalNotPermitted createRenewalNotPermitted() {
        return new RenewalNotPermitted();
    }

    /**
     * Create an instance of {@link LoanedItemCountValue }
     * 
     */
    public LoanedItemCountValue createLoanedItemCountValue() {
        return new LoanedItemCountValue();
    }

    /**
     * Create an instance of {@link ProcessingError }
     * 
     */
    public ProcessingError createProcessingError() {
        return new ProcessingError();
    }

    /**
     * Create an instance of {@link FiscalActionType }
     * 
     */
    public FiscalActionType createFiscalActionType() {
        return new FiscalActionType();
    }

    /**
     * Create an instance of {@link FiscalTransactionReferenceId }
     * 
     */
    public FiscalTransactionReferenceId createFiscalTransactionReferenceId() {
        return new FiscalTransactionReferenceId();
    }

    /**
     * Create an instance of {@link FiscalTransactionType }
     * 
     */
    public FiscalTransactionType createFiscalTransactionType() {
        return new FiscalTransactionType();
    }

    /**
     * Create an instance of {@link ValidFromDate }
     * 
     */
    public ValidFromDate createValidFromDate() {
        return new ValidFromDate();
    }

    /**
     * Create an instance of {@link ValidToDate }
     * 
     */
    public ValidToDate createValidToDate() {
        return new ValidToDate();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link FiscalTransactionDescription }
     * 
     */
    public FiscalTransactionDescription createFiscalTransactionDescription() {
        return new FiscalTransactionDescription();
    }

    /**
     * Create an instance of {@link ItemDetails }
     * 
     */
    public ItemDetails createItemDetails() {
        return new ItemDetails();
    }

    /**
     * Create an instance of {@link BinNumber }
     * 
     */
    public BinNumber createBinNumber() {
        return new BinNumber();
    }

    /**
     * Create an instance of {@link HoldingsInformation }
     * 
     */
    public HoldingsInformation createHoldingsInformation() {
        return new HoldingsInformation();
    }

    /**
     * Create an instance of {@link ItemReportedLost }
     * 
     */
    public ItemReportedLost createItemReportedLost() {
        return new ItemReportedLost();
    }

    /**
     * Create an instance of {@link OrganizationName }
     * 
     */
    public OrganizationName createOrganizationName() {
        return new OrganizationName();
    }

    /**
     * Create an instance of {@link DateAvailable }
     * 
     */
    public DateAvailable createDateAvailable() {
        return new DateAvailable();
    }

    /**
     * Create an instance of {@link CopyNumber }
     * 
     */
    public CopyNumber createCopyNumber() {
        return new CopyNumber();
    }

    /**
     * Create an instance of {@link VisibleUserId }
     * 
     */
    public VisibleUserId createVisibleUserId() {
        return new VisibleUserId();
    }

    /**
     * Create an instance of {@link UserAddressInformation }
     * 
     */
    public UserAddressInformation createUserAddressInformation() {
        return new UserAddressInformation();
    }

    /**
     * Create an instance of {@link DateOfBirth }
     * 
     */
    public DateOfBirth createDateOfBirth() {
        return new DateOfBirth();
    }

    /**
     * Create an instance of {@link UserLanguage }
     * 
     */
    public UserLanguage createUserLanguage() {
        return new UserLanguage();
    }

    /**
     * Create an instance of {@link UserPrivilege }
     * 
     */
    public UserPrivilege createUserPrivilege() {
        return new UserPrivilege();
    }

    /**
     * Create an instance of {@link BlockOrTrap }
     * 
     */
    public BlockOrTrap createBlockOrTrap() {
        return new BlockOrTrap();
    }

    /**
     * Create an instance of {@link VisibleUserIdentifier }
     * 
     */
    public VisibleUserIdentifier createVisibleUserIdentifier() {
        return new VisibleUserIdentifier();
    }

    /**
     * Create an instance of {@link RequestedItemCountValue }
     * 
     */
    public RequestedItemCountValue createRequestedItemCountValue() {
        return new RequestedItemCountValue();
    }

    /**
     * Create an instance of {@link VisibleItemIdentifierType }
     * 
     */
    public VisibleItemIdentifierType createVisibleItemIdentifierType() {
        return new VisibleItemIdentifierType();
    }

    /**
     * Create an instance of {@link LoanedItemsDesired }
     * 
     */
    public LoanedItemsDesired createLoanedItemsDesired() {
        return new LoanedItemsDesired();
    }

    /**
     * Create an instance of {@link DateRecalled }
     * 
     */
    public DateRecalled createDateRecalled() {
        return new DateRecalled();
    }

    /**
     * Create an instance of {@link Suffix }
     * 
     */
    public Suffix createSuffix() {
        return new Suffix();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link RequestedItemsDesired }
     * 
     */
    public RequestedItemsDesired createRequestedItemsDesired() {
        return new RequestedItemsDesired();
    }

    /**
     * Create an instance of {@link UserFiscalAccountDesired }
     * 
     */
    public UserFiscalAccountDesired createUserFiscalAccountDesired() {
        return new UserFiscalAccountDesired();
    }

    /**
     * Create an instance of {@link ApplicationProfileType }
     * 
     */
    public ApplicationProfileType createApplicationProfileType() {
        return new ApplicationProfileType();
    }

    /**
     * Create an instance of {@link OrganizationNameType }
     * 
     */
    public OrganizationNameType createOrganizationNameType() {
        return new OrganizationNameType();
    }

    /**
     * Create an instance of {@link ItemTransaction }
     * 
     */
    public ItemTransaction createItemTransaction() {
        return new ItemTransaction();
    }

    /**
     * Create an instance of {@link CurrentRequester }
     * 
     */
    public CurrentRequester createCurrentRequester() {
        return new CurrentRequester();
    }

    /**
     * Create an instance of {@link DateEventOccurred }
     * 
     */
    public DateEventOccurred createDateEventOccurred() {
        return new DateEventOccurred();
    }

    /**
     * Create an instance of {@link UnstructuredAddressType }
     * 
     */
    public UnstructuredAddressType createUnstructuredAddressType() {
        return new UnstructuredAddressType();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link UserPrivilegeStatus }
     * 
     */
    public UserPrivilegeStatus createUserPrivilegeStatus() {
        return new UserPrivilegeStatus();
    }

    /**
     * Create an instance of {@link UserPrivilegeStatusType }
     * 
     */
    public UserPrivilegeStatusType createUserPrivilegeStatusType() {
        return new UserPrivilegeStatusType();
    }

    /**
     * Create an instance of {@link DateOfUserPrivilegeStatus }
     * 
     */
    public DateOfUserPrivilegeStatus createDateOfUserPrivilegeStatus() {
        return new DateOfUserPrivilegeStatus();
    }

    /**
     * Create an instance of {@link AgencyAddressInformation }
     * 
     */
    public AgencyAddressInformation createAgencyAddressInformation() {
        return new AgencyAddressInformation();
    }

    /**
     * Create an instance of {@link AuthenticationPrompt }
     * 
     */
    public AuthenticationPrompt createAuthenticationPrompt() {
        return new AuthenticationPrompt();
    }

    /**
     * Create an instance of {@link ApplicationProfileSupportedType }
     * 
     */
    public ApplicationProfileSupportedType createApplicationProfileSupportedType() {
        return new ApplicationProfileSupportedType();
    }

    /**
     * Create an instance of {@link ConsortiumAgreement }
     * 
     */
    public ConsortiumAgreement createConsortiumAgreement() {
        return new ConsortiumAgreement();
    }

    /**
     * Create an instance of {@link AgencyUserPrivilegeType }
     * 
     */
    public AgencyUserPrivilegeType createAgencyUserPrivilegeType() {
        return new AgencyUserPrivilegeType();
    }

    /**
     * Create an instance of {@link AgencyAddressRoleType }
     * 
     */
    public AgencyAddressRoleType createAgencyAddressRoleType() {
        return new AgencyAddressRoleType();
    }

    /**
     * Create an instance of {@link BlockOrTrapType }
     * 
     */
    public BlockOrTrapType createBlockOrTrapType() {
        return new BlockOrTrapType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link BibliographicRecordId }
     * 
     */
    public BibliographicRecordId createBibliographicRecordId() {
        return new BibliographicRecordId();
    }

    /**
     * Create an instance of {@link PromptOutput }
     * 
     */
    public PromptOutput createPromptOutput() {
        return new PromptOutput();
    }

    /**
     * Create an instance of {@link NoticeItem }
     * 
     */
    public NoticeItem createNoticeItem() {
        return new NoticeItem();
    }

    /**
     * Create an instance of {@link SponsoringBody }
     * 
     */
    public SponsoringBody createSponsoringBody() {
        return new SponsoringBody();
    }

    /**
     * Create an instance of {@link ItemDescriptionLevel }
     * 
     */
    public ItemDescriptionLevel createItemDescriptionLevel() {
        return new ItemDescriptionLevel();
    }

    /**
     * Create an instance of {@link BibliographicLevel }
     * 
     */
    public BibliographicLevel createBibliographicLevel() {
        return new BibliographicLevel();
    }

    /**
     * Create an instance of {@link DateCheckedOut }
     * 
     */
    public DateCheckedOut createDateCheckedOut() {
        return new DateCheckedOut();
    }

    /**
     * Create an instance of {@link DeleteUserFields }
     * 
     */
    public DeleteUserFields createDeleteUserFields() {
        return new DeleteUserFields();
    }

    /**
     * Create an instance of {@link AddUserFields }
     * 
     */
    public AddUserFields createAddUserFields() {
        return new AddUserFields();
    }

    /**
     * Create an instance of {@link SeriesTitleNumber }
     * 
     */
    public SeriesTitleNumber createSeriesTitleNumber() {
        return new SeriesTitleNumber();
    }

    /**
     * Create an instance of {@link MediumType }
     * 
     */
    public MediumType createMediumType() {
        return new MediumType();
    }

    /**
     * Create an instance of {@link PhysicalAddressType }
     * 
     */
    public PhysicalAddressType createPhysicalAddressType() {
        return new PhysicalAddressType();
    }

    /**
     * Create an instance of {@link UserIdentifierValue }
     * 
     */
    public UserIdentifierValue createUserIdentifierValue() {
        return new UserIdentifierValue();
    }

    /**
     * Create an instance of {@link Edition }
     * 
     */
    public Edition createEdition() {
        return new Edition();
    }

    /**
     * Create an instance of {@link UserPrivilegeFee }
     * 
     */
    public UserPrivilegeFee createUserPrivilegeFee() {
        return new UserPrivilegeFee();
    }

    /**
     * Create an instance of {@link ItemReportedNeverBorrowed }
     * 
     */
    public ItemReportedNeverBorrowed createItemReportedNeverBorrowed() {
        return new ItemReportedNeverBorrowed();
    }

    /**
     * Create an instance of {@link UnstructuredAddress }
     * 
     */
    public UnstructuredAddress createUnstructuredAddress() {
        return new UnstructuredAddress();
    }

    /**
     * Create an instance of {@link SensitiveDataFlag }
     * 
     */
    public SensitiveDataFlag createSensitiveDataFlag() {
        return new SensitiveDataFlag();
    }

    /**
     * Create an instance of {@link UserAddressRoleType }
     * 
     */
    public UserAddressRoleType createUserAddressRoleType() {
        return new UserAddressRoleType();
    }

    /**
     * Create an instance of {@link PhysicalConditionType }
     * 
     */
    public PhysicalConditionType createPhysicalConditionType() {
        return new PhysicalConditionType();
    }

    /**
     * Create an instance of {@link PromptInput }
     * 
     */
    public PromptInput createPromptInput() {
        return new PromptInput();
    }

    /**
     * Create an instance of {@link AuthenticationInputType }
     * 
     */
    public AuthenticationInputType createAuthenticationInputType() {
        return new AuthenticationInputType();
    }

    /**
     * Create an instance of {@link VisibleUserIdentifierType }
     * 
     */
    public VisibleUserIdentifierType createVisibleUserIdentifierType() {
        return new VisibleUserIdentifierType();
    }

    /**
     * Create an instance of {@link UniqueBibliographicId }
     * 
     */
    public UniqueBibliographicId createUniqueBibliographicId() {
        return new UniqueBibliographicId();
    }

    /**
     * Create an instance of {@link ItemReportedReturned }
     * 
     */
    public ItemReportedReturned createItemReportedReturned() {
        return new ItemReportedReturned();
    }

    /**
     * Create an instance of {@link UserNoticeDetails }
     * 
     */
    public UserNoticeDetails createUserNoticeDetails() {
        return new UserNoticeDetails();
    }

    /**
     * Create an instance of {@link NoticeType }
     * 
     */
    public NoticeType createNoticeType() {
        return new NoticeType();
    }

    /**
     * Create an instance of {@link NoticeContent }
     * 
     */
    public NoticeContent createNoticeContent() {
        return new NoticeContent();
    }

    /**
     * Create an instance of {@link DateOfUserRequest }
     * 
     */
    public DateOfUserRequest createDateOfUserRequest() {
        return new DateOfUserRequest();
    }

    /**
     * Create an instance of {@link ResourceDesired }
     * 
     */
    public ResourceDesired createResourceDesired() {
        return new ResourceDesired();
    }

    /**
     * Create an instance of {@link MessagingErrorType }
     * 
     */
    public MessagingErrorType createMessagingErrorType() {
        return new MessagingErrorType();
    }

    /**
     * Create an instance of {@link DateToSend }
     * 
     */
    public DateToSend createDateToSend() {
        return new DateToSend();
    }

    /**
     * Create an instance of {@link VisibleItemId }
     * 
     */
    public VisibleItemId createVisibleItemId() {
        return new VisibleItemId();
    }

    /**
     * Create an instance of {@link VisibleItemIdentifier }
     * 
     */
    public VisibleItemIdentifier createVisibleItemIdentifier() {
        return new VisibleItemIdentifier();
    }

    /**
     * Create an instance of {@link Pagination }
     * 
     */
    public Pagination createPagination() {
        return new Pagination();
    }

    /**
     * Create an instance of {@link PublicationDate }
     * 
     */
    public PublicationDate createPublicationDate() {
        return new PublicationDate();
    }

    /**
     * Create an instance of {@link CurrentBorrowerDesired }
     * 
     */
    public CurrentBorrowerDesired createCurrentBorrowerDesired() {
        return new CurrentBorrowerDesired();
    }

    /**
     * Create an instance of {@link UserPrivilegeDescription }
     * 
     */
    public UserPrivilegeDescription createUserPrivilegeDescription() {
        return new UserPrivilegeDescription();
    }

    /**
     * Create an instance of {@link RequestedActionType }
     * 
     */
    public RequestedActionType createRequestedActionType() {
        return new RequestedActionType();
    }

    /**
     * Create an instance of {@link ItemReportedMissing }
     * 
     */
    public ItemReportedMissing createItemReportedMissing() {
        return new ItemReportedMissing();
    }

    /**
     * Create an instance of {@link IndeterminateLoanPeriodFlag }
     * 
     */
    public IndeterminateLoanPeriodFlag createIndeterminateLoanPeriodFlag() {
        return new IndeterminateLoanPeriodFlag();
    }

    /**
     * Create an instance of {@link LoanedItem }
     * 
     */
    public LoanedItem createLoanedItem() {
        return new LoanedItem();
    }

    /**
     * Create an instance of {@link DateOfExpectedReply }
     * 
     */
    public DateOfExpectedReply createDateOfExpectedReply() {
        return new DateOfExpectedReply();
    }

    /**
     * Create an instance of {@link AuthenticationInputData }
     * 
     */
    public AuthenticationInputData createAuthenticationInputData() {
        return new AuthenticationInputData();
    }

    /**
     * Create an instance of {@link NonReturnableFlag }
     * 
     */
    public NonReturnableFlag createNonReturnableFlag() {
        return new NonReturnableFlag();
    }

    /**
     * Create an instance of {@link DateRenewed }
     * 
     */
    public DateRenewed createDateRenewed() {
        return new DateRenewed();
    }

    /**
     * Create an instance of {@link ElectronicResourceProvidedFlag }
     * 
     */
    public ElectronicResourceProvidedFlag createElectronicResourceProvidedFlag() {
        return new ElectronicResourceProvidedFlag();
    }

}
