//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "physicalConditionType",
    "physicalConditionDetails"
})
@XmlRootElement(name = "PhysicalCondition")
public class PhysicalCondition {

    @XmlElement(name = "PhysicalConditionType", required = true)
    protected PhysicalConditionType physicalConditionType;
    @XmlElement(name = "PhysicalConditionDetails")
    protected PhysicalConditionDetails physicalConditionDetails;

    /**
     * Gets the value of the physicalConditionType property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalConditionType }
     *     
     */
    public PhysicalConditionType getPhysicalConditionType() {
        return physicalConditionType;
    }

    /**
     * Sets the value of the physicalConditionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalConditionType }
     *     
     */
    public void setPhysicalConditionType(PhysicalConditionType value) {
        this.physicalConditionType = value;
    }

    /**
     * Gets the value of the physicalConditionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalConditionDetails }
     *     
     */
    public PhysicalConditionDetails getPhysicalConditionDetails() {
        return physicalConditionDetails;
    }

    /**
     * Sets the value of the physicalConditionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalConditionDetails }
     *     
     */
    public void setPhysicalConditionDetails(PhysicalConditionDetails value) {
        this.physicalConditionDetails = value;
    }

}
