//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processingErrorType",
    "processingErrorElement"
})
@XmlRootElement(name = "ProcessingError")
public class ProcessingError {

    @XmlElement(name = "ProcessingErrorType", required = true)
    protected ProcessingErrorType processingErrorType;
    @XmlElement(name = "ProcessingErrorElement", required = true)
    protected ProcessingErrorElement processingErrorElement;

    /**
     * Gets the value of the processingErrorType property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingErrorType }
     *     
     */
    public ProcessingErrorType getProcessingErrorType() {
        return processingErrorType;
    }

    /**
     * Sets the value of the processingErrorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingErrorType }
     *     
     */
    public void setProcessingErrorType(ProcessingErrorType value) {
        this.processingErrorType = value;
    }

    /**
     * Gets the value of the processingErrorElement property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingErrorElement }
     *     
     */
    public ProcessingErrorElement getProcessingErrorElement() {
        return processingErrorElement;
    }

    /**
     * Sets the value of the processingErrorElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingErrorElement }
     *     
     */
    public void setProcessingErrorElement(ProcessingErrorElement value) {
        this.processingErrorElement = value;
    }

}
