//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authenticationInputType",
    "authenticationDataFormatType",
    "sensitiveDataFlag"
})
@XmlRootElement(name = "PromptInput")
public class PromptInput {

    @XmlElement(name = "AuthenticationInputType", required = true)
    protected AuthenticationInputType authenticationInputType;
    @XmlElement(name = "AuthenticationDataFormatType", required = true)
    protected AuthenticationDataFormatType authenticationDataFormatType;
    @XmlElement(name = "SensitiveDataFlag")
    protected SensitiveDataFlag sensitiveDataFlag;

    /**
     * Gets the value of the authenticationInputType property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationInputType }
     *     
     */
    public AuthenticationInputType getAuthenticationInputType() {
        return authenticationInputType;
    }

    /**
     * Sets the value of the authenticationInputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationInputType }
     *     
     */
    public void setAuthenticationInputType(AuthenticationInputType value) {
        this.authenticationInputType = value;
    }

    /**
     * Gets the value of the authenticationDataFormatType property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationDataFormatType }
     *     
     */
    public AuthenticationDataFormatType getAuthenticationDataFormatType() {
        return authenticationDataFormatType;
    }

    /**
     * Sets the value of the authenticationDataFormatType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationDataFormatType }
     *     
     */
    public void setAuthenticationDataFormatType(AuthenticationDataFormatType value) {
        this.authenticationDataFormatType = value;
    }

    /**
     * Gets the value of the sensitiveDataFlag property.
     * 
     * @return
     *     possible object is
     *     {@link SensitiveDataFlag }
     *     
     */
    public SensitiveDataFlag getSensitiveDataFlag() {
        return sensitiveDataFlag;
    }

    /**
     * Sets the value of the sensitiveDataFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link SensitiveDataFlag }
     *     
     */
    public void setSensitiveDataFlag(SensitiveDataFlag value) {
        this.sensitiveDataFlag = value;
    }

}
