//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestTypeOrCirculationStatusOrItemUseRestrictionType",
    "requestedItemCountValue"
})
@XmlRootElement(name = "RequestedItemsCount")
public class RequestedItemsCount {

    @XmlElements({
        @XmlElement(name = "RequestType", required = true, type = RequestType.class),
        @XmlElement(name = "CirculationStatus", required = true, type = CirculationStatus.class),
        @XmlElement(name = "ItemUseRestrictionType", required = true, type = ItemUseRestrictionType.class)
    })
    protected List<Object> requestTypeOrCirculationStatusOrItemUseRestrictionType;
    @XmlElement(name = "RequestedItemCountValue", required = true)
    protected RequestedItemCountValue requestedItemCountValue;

    /**
     * Gets the value of the requestTypeOrCirculationStatusOrItemUseRestrictionType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestTypeOrCirculationStatusOrItemUseRestrictionType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestTypeOrCirculationStatusOrItemUseRestrictionType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestType }
     * {@link CirculationStatus }
     * {@link ItemUseRestrictionType }
     * 
     * 
     */
    public List<Object> getRequestTypeOrCirculationStatusOrItemUseRestrictionType() {
        if (requestTypeOrCirculationStatusOrItemUseRestrictionType == null) {
            requestTypeOrCirculationStatusOrItemUseRestrictionType = new ArrayList<Object>();
        }
        return this.requestTypeOrCirculationStatusOrItemUseRestrictionType;
    }

    /**
     * Gets the value of the requestedItemCountValue property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedItemCountValue }
     *     
     */
    public RequestedItemCountValue getRequestedItemCountValue() {
        return requestedItemCountValue;
    }

    /**
     * Sets the value of the requestedItemCountValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedItemCountValue }
     *     
     */
    public void setRequestedItemCountValue(RequestedItemCountValue value) {
        this.requestedItemCountValue = value;
    }

}
