//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueItemIdOrUniqueRequestId",
    "requestType",
    "requestStatusType",
    "datePlaced",
    "pickupDate",
    "pickupExpiryDate",
    "reminderLevel",
    "holdQueuePosition"
})
@XmlRootElement(name = "RequestedItem")
public class RequestedItem {

    @XmlElements({
        @XmlElement(name = "UniqueItemId", required = true, type = UniqueItemId.class),
        @XmlElement(name = "UniqueRequestId", required = true, type = UniqueRequestId.class)
    })
    protected List<Object> uniqueItemIdOrUniqueRequestId;
    @XmlElement(name = "RequestType", required = true)
    protected RequestType requestType;
    @XmlElement(name = "RequestStatusType", required = true)
    protected RequestStatusType requestStatusType;
    @XmlElement(name = "DatePlaced", required = true)
    protected DatePlaced datePlaced;
    @XmlElement(name = "PickupDate")
    protected PickupDate pickupDate;
    @XmlElement(name = "PickupExpiryDate")
    protected PickupExpiryDate pickupExpiryDate;
    @XmlElement(name = "ReminderLevel")
    protected ReminderLevel reminderLevel;
    @XmlElement(name = "HoldQueuePosition")
    protected HoldQueuePosition holdQueuePosition;

    /**
     * Gets the value of the uniqueItemIdOrUniqueRequestId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uniqueItemIdOrUniqueRequestId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniqueItemIdOrUniqueRequestId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UniqueItemId }
     * {@link UniqueRequestId }
     * 
     * 
     */
    public List<Object> getUniqueItemIdOrUniqueRequestId() {
        if (uniqueItemIdOrUniqueRequestId == null) {
            uniqueItemIdOrUniqueRequestId = new ArrayList<Object>();
        }
        return this.uniqueItemIdOrUniqueRequestId;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType }
     *     
     */
    public RequestType getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType }
     *     
     */
    public void setRequestType(RequestType value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the requestStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link RequestStatusType }
     *     
     */
    public RequestStatusType getRequestStatusType() {
        return requestStatusType;
    }

    /**
     * Sets the value of the requestStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestStatusType }
     *     
     */
    public void setRequestStatusType(RequestStatusType value) {
        this.requestStatusType = value;
    }

    /**
     * Gets the value of the datePlaced property.
     * 
     * @return
     *     possible object is
     *     {@link DatePlaced }
     *     
     */
    public DatePlaced getDatePlaced() {
        return datePlaced;
    }

    /**
     * Sets the value of the datePlaced property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatePlaced }
     *     
     */
    public void setDatePlaced(DatePlaced value) {
        this.datePlaced = value;
    }

    /**
     * Gets the value of the pickupDate property.
     * 
     * @return
     *     possible object is
     *     {@link PickupDate }
     *     
     */
    public PickupDate getPickupDate() {
        return pickupDate;
    }

    /**
     * Sets the value of the pickupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PickupDate }
     *     
     */
    public void setPickupDate(PickupDate value) {
        this.pickupDate = value;
    }

    /**
     * Gets the value of the pickupExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link PickupExpiryDate }
     *     
     */
    public PickupExpiryDate getPickupExpiryDate() {
        return pickupExpiryDate;
    }

    /**
     * Sets the value of the pickupExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PickupExpiryDate }
     *     
     */
    public void setPickupExpiryDate(PickupExpiryDate value) {
        this.pickupExpiryDate = value;
    }

    /**
     * Gets the value of the reminderLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ReminderLevel }
     *     
     */
    public ReminderLevel getReminderLevel() {
        return reminderLevel;
    }

    /**
     * Sets the value of the reminderLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReminderLevel }
     *     
     */
    public void setReminderLevel(ReminderLevel value) {
        this.reminderLevel = value;
    }

    /**
     * Gets the value of the holdQueuePosition property.
     * 
     * @return
     *     possible object is
     *     {@link HoldQueuePosition }
     *     
     */
    public HoldQueuePosition getHoldQueuePosition() {
        return holdQueuePosition;
    }

    /**
     * Sets the value of the holdQueuePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link HoldQueuePosition }
     *     
     */
    public void setHoldQueuePosition(HoldQueuePosition value) {
        this.holdQueuePosition = value;
    }

}
