//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiationHeader",
    "mandatedAction",
    "uniqueUserId",
    "dateToSend",
    "userNoticeDetails"
})
@XmlRootElement(name = "SendUserNotice")
public class SendUserNotice {

    @XmlElement(name = "InitiationHeader", required = true)
    protected InitiationHeader initiationHeader;
    @XmlElement(name = "MandatedAction")
    protected MandatedAction mandatedAction;
    @XmlElement(name = "UniqueUserId", required = true)
    protected UniqueUserId uniqueUserId;
    @XmlElement(name = "DateToSend")
    protected DateToSend dateToSend;
    @XmlElement(name = "UserNoticeDetails", required = true)
    protected UserNoticeDetails userNoticeDetails;

    /**
     * Gets the value of the initiationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InitiationHeader }
     *     
     */
    public InitiationHeader getInitiationHeader() {
        return initiationHeader;
    }

    /**
     * Sets the value of the initiationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiationHeader }
     *     
     */
    public void setInitiationHeader(InitiationHeader value) {
        this.initiationHeader = value;
    }

    /**
     * Gets the value of the mandatedAction property.
     * 
     * @return
     *     possible object is
     *     {@link MandatedAction }
     *     
     */
    public MandatedAction getMandatedAction() {
        return mandatedAction;
    }

    /**
     * Sets the value of the mandatedAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandatedAction }
     *     
     */
    public void setMandatedAction(MandatedAction value) {
        this.mandatedAction = value;
    }

    /**
     * Gets the value of the uniqueUserId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueUserId }
     *     
     */
    public UniqueUserId getUniqueUserId() {
        return uniqueUserId;
    }

    /**
     * Sets the value of the uniqueUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueUserId }
     *     
     */
    public void setUniqueUserId(UniqueUserId value) {
        this.uniqueUserId = value;
    }

    /**
     * Gets the value of the dateToSend property.
     * 
     * @return
     *     possible object is
     *     {@link DateToSend }
     *     
     */
    public DateToSend getDateToSend() {
        return dateToSend;
    }

    /**
     * Sets the value of the dateToSend property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateToSend }
     *     
     */
    public void setDateToSend(DateToSend value) {
        this.dateToSend = value;
    }

    /**
     * Gets the value of the userNoticeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link UserNoticeDetails }
     *     
     */
    public UserNoticeDetails getUserNoticeDetails() {
        return userNoticeDetails;
    }

    /**
     * Sets the value of the userNoticeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserNoticeDetails }
     *     
     */
    public void setUserNoticeDetails(UserNoticeDetails value) {
        this.userNoticeDetails = value;
    }

}
