//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shippingInstructions",
    "shippingNote",
    "physicalAddressOrElectronicAddress"
})
@XmlRootElement(name = "ShippingInformation")
public class ShippingInformation {

    @XmlElement(name = "ShippingInstructions")
    protected ShippingInstructions shippingInstructions;
    @XmlElement(name = "ShippingNote")
    protected ShippingNote shippingNote;
    @XmlElements({
        @XmlElement(name = "PhysicalAddress", required = true, type = PhysicalAddress.class),
        @XmlElement(name = "ElectronicAddress", required = true, type = ElectronicAddress.class)
    })
    protected List<Object> physicalAddressOrElectronicAddress;

    /**
     * Gets the value of the shippingInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingInstructions }
     *     
     */
    public ShippingInstructions getShippingInstructions() {
        return shippingInstructions;
    }

    /**
     * Sets the value of the shippingInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingInstructions }
     *     
     */
    public void setShippingInstructions(ShippingInstructions value) {
        this.shippingInstructions = value;
    }

    /**
     * Gets the value of the shippingNote property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingNote }
     *     
     */
    public ShippingNote getShippingNote() {
        return shippingNote;
    }

    /**
     * Sets the value of the shippingNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingNote }
     *     
     */
    public void setShippingNote(ShippingNote value) {
        this.shippingNote = value;
    }

    /**
     * Gets the value of the physicalAddressOrElectronicAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAddressOrElectronicAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAddressOrElectronicAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalAddress }
     * {@link ElectronicAddress }
     * 
     * 
     */
    public List<Object> getPhysicalAddressOrElectronicAddress() {
        if (physicalAddressOrElectronicAddress == null) {
            physicalAddressOrElectronicAddress = new ArrayList<Object>();
        }
        return this.physicalAddressOrElectronicAddress;
    }

}
