//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locationWithinBuildingOrHouseNameOrDistrictOrPostOfficeBoxOrStreetOrLine1OrLine2",
    "locality",
    "region",
    "country",
    "postalCode",
    "careOf"
})
@XmlRootElement(name = "StructuredAddress")
public class StructuredAddress {

    @XmlElements({
        @XmlElement(name = "LocationWithinBuilding", required = true, type = LocationWithinBuilding.class),
        @XmlElement(name = "HouseName", required = true, type = HouseName.class),
        @XmlElement(name = "District", required = true, type = District.class),
        @XmlElement(name = "PostOfficeBox", required = true, type = PostOfficeBox.class),
        @XmlElement(name = "Street", required = true, type = Street.class),
        @XmlElement(name = "Line1", required = true, type = Line1 .class),
        @XmlElement(name = "Line2", required = true, type = Line2 .class)
    })
    protected List<Object> locationWithinBuildingOrHouseNameOrDistrictOrPostOfficeBoxOrStreetOrLine1OrLine2;
    @XmlElement(name = "Locality")
    protected Locality locality;
    @XmlElement(name = "Region")
    protected Region region;
    @XmlElement(name = "Country")
    protected Country country;
    @XmlElement(name = "PostalCode")
    protected PostalCode postalCode;
    @XmlElement(name = "CareOf")
    protected CareOf careOf;

    /**
     * Gets the value of the locationWithinBuildingOrHouseNameOrDistrictOrPostOfficeBoxOrStreetOrLine1OrLine2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locationWithinBuildingOrHouseNameOrDistrictOrPostOfficeBoxOrStreetOrLine1OrLine2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationWithinBuildingOrHouseNameOrDistrictOrPostOfficeBoxOrStreetOrLine1OrLine2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationWithinBuilding }
     * {@link HouseName }
     * {@link District }
     * {@link PostOfficeBox }
     * {@link Street }
     * {@link Line1 }
     * {@link Line2 }
     * 
     * 
     */
    public List<Object> getLocationWithinBuildingOrHouseNameOrDistrictOrPostOfficeBoxOrStreetOrLine1OrLine2() {
        if (locationWithinBuildingOrHouseNameOrDistrictOrPostOfficeBoxOrStreetOrLine1OrLine2 == null) {
            locationWithinBuildingOrHouseNameOrDistrictOrPostOfficeBoxOrStreetOrLine1OrLine2 = new ArrayList<Object>();
        }
        return this.locationWithinBuildingOrHouseNameOrDistrictOrPostOfficeBoxOrStreetOrLine1OrLine2;
    }

    /**
     * Gets the value of the locality property.
     * 
     * @return
     *     possible object is
     *     {@link Locality }
     *     
     */
    public Locality getLocality() {
        return locality;
    }

    /**
     * Sets the value of the locality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Locality }
     *     
     */
    public void setLocality(Locality value) {
        this.locality = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link Region }
     *     
     */
    public Region getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link Region }
     *     
     */
    public void setRegion(Region value) {
        this.region = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountry(Country value) {
        this.country = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link PostalCode }
     *     
     */
    public PostalCode getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostalCode }
     *     
     */
    public void setPostalCode(PostalCode value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the careOf property.
     * 
     * @return
     *     possible object is
     *     {@link CareOf }
     *     
     */
    public CareOf getCareOf() {
        return careOf;
    }

    /**
     * Sets the value of the careOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link CareOf }
     *     
     */
    public void setCareOf(CareOf value) {
        this.careOf = value;
    }

}
