//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unstructuredAddressType",
    "unstructuredAddressData"
})
@XmlRootElement(name = "UnstructuredAddress")
public class UnstructuredAddress {

    @XmlElement(name = "UnstructuredAddressType", required = true)
    protected UnstructuredAddressType unstructuredAddressType;
    @XmlElement(name = "UnstructuredAddressData", required = true)
    protected UnstructuredAddressData unstructuredAddressData;

    /**
     * Gets the value of the unstructuredAddressType property.
     * 
     * @return
     *     possible object is
     *     {@link UnstructuredAddressType }
     *     
     */
    public UnstructuredAddressType getUnstructuredAddressType() {
        return unstructuredAddressType;
    }

    /**
     * Sets the value of the unstructuredAddressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnstructuredAddressType }
     *     
     */
    public void setUnstructuredAddressType(UnstructuredAddressType value) {
        this.unstructuredAddressType = value;
    }

    /**
     * Gets the value of the unstructuredAddressData property.
     * 
     * @return
     *     possible object is
     *     {@link UnstructuredAddressData }
     *     
     */
    public UnstructuredAddressData getUnstructuredAddressData() {
        return unstructuredAddressData;
    }

    /**
     * Sets the value of the unstructuredAddressData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnstructuredAddressData }
     *     
     */
    public void setUnstructuredAddressData(UnstructuredAddressData value) {
        this.unstructuredAddressData = value;
    }

}
