//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestedItem",
    "loanedItem"
})
@XmlRootElement(name = "UserTransaction")
public class UserTransaction {

    @XmlElement(name = "RequestedItem")
    protected List<RequestedItem> requestedItem;
    @XmlElement(name = "LoanedItem")
    protected List<LoanedItem> loanedItem;

    /**
     * Gets the value of the requestedItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestedItem }
     * 
     * 
     */
    public List<RequestedItem> getRequestedItem() {
        if (requestedItem == null) {
            requestedItem = new ArrayList<RequestedItem>();
        }
        return this.requestedItem;
    }

    /**
     * Gets the value of the loanedItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loanedItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoanedItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoanedItem }
     * 
     * 
     */
    public List<LoanedItem> getLoanedItem() {
        if (loanedItem == null) {
            loanedItem = new ArrayList<LoanedItem>();
        }
        return this.loanedItem;
    }

}
