//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userPrivilegeStatusType",
    "dateOfUserPrivilegeStatus"
})
@XmlRootElement(name = "UserPrivilegeStatus")
public class UserPrivilegeStatus {

    @XmlElement(name = "UserPrivilegeStatusType", required = true)
    protected UserPrivilegeStatusType userPrivilegeStatusType;
    @XmlElement(name = "DateOfUserPrivilegeStatus")
    protected DateOfUserPrivilegeStatus dateOfUserPrivilegeStatus;

    /**
     * Gets the value of the userPrivilegeStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link UserPrivilegeStatusType }
     *     
     */
    public UserPrivilegeStatusType getUserPrivilegeStatusType() {
        return userPrivilegeStatusType;
    }

    /**
     * Sets the value of the userPrivilegeStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPrivilegeStatusType }
     *     
     */
    public void setUserPrivilegeStatusType(UserPrivilegeStatusType value) {
        this.userPrivilegeStatusType = value;
    }

    /**
     * Gets the value of the dateOfUserPrivilegeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DateOfUserPrivilegeStatus }
     *     
     */
    public DateOfUserPrivilegeStatus getDateOfUserPrivilegeStatus() {
        return dateOfUserPrivilegeStatus;
    }

    /**
     * Sets the value of the dateOfUserPrivilegeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateOfUserPrivilegeStatus }
     *     
     */
    public void setDateOfUserPrivilegeStatus(DateOfUserPrivilegeStatus value) {
        this.dateOfUserPrivilegeStatus = value;
    }

}
