//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueAgencyId",
    "agencyUserPrivilegeType",
    "validFromDate",
    "validToDate",
    "userPrivilegeFee",
    "userPrivilegeStatus",
    "userPrivilegeDescription"
})
@XmlRootElement(name = "UserPrivilege")
public class UserPrivilege {

    @XmlElement(name = "UniqueAgencyId", required = true)
    protected UniqueAgencyId uniqueAgencyId;
    @XmlElement(name = "AgencyUserPrivilegeType", required = true)
    protected AgencyUserPrivilegeType agencyUserPrivilegeType;
    @XmlElement(name = "ValidFromDate")
    protected ValidFromDate validFromDate;
    @XmlElement(name = "ValidToDate")
    protected ValidToDate validToDate;
    @XmlElement(name = "UserPrivilegeFee")
    protected UserPrivilegeFee userPrivilegeFee;
    @XmlElement(name = "UserPrivilegeStatus")
    protected UserPrivilegeStatus userPrivilegeStatus;
    @XmlElement(name = "UserPrivilegeDescription")
    protected UserPrivilegeDescription userPrivilegeDescription;

    /**
     * Gets the value of the uniqueAgencyId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueAgencyId }
     *     
     */
    public UniqueAgencyId getUniqueAgencyId() {
        return uniqueAgencyId;
    }

    /**
     * Sets the value of the uniqueAgencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueAgencyId }
     *     
     */
    public void setUniqueAgencyId(UniqueAgencyId value) {
        this.uniqueAgencyId = value;
    }

    /**
     * Gets the value of the agencyUserPrivilegeType property.
     * 
     * @return
     *     possible object is
     *     {@link AgencyUserPrivilegeType }
     *     
     */
    public AgencyUserPrivilegeType getAgencyUserPrivilegeType() {
        return agencyUserPrivilegeType;
    }

    /**
     * Sets the value of the agencyUserPrivilegeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgencyUserPrivilegeType }
     *     
     */
    public void setAgencyUserPrivilegeType(AgencyUserPrivilegeType value) {
        this.agencyUserPrivilegeType = value;
    }

    /**
     * Gets the value of the validFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link ValidFromDate }
     *     
     */
    public ValidFromDate getValidFromDate() {
        return validFromDate;
    }

    /**
     * Sets the value of the validFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidFromDate }
     *     
     */
    public void setValidFromDate(ValidFromDate value) {
        this.validFromDate = value;
    }

    /**
     * Gets the value of the validToDate property.
     * 
     * @return
     *     possible object is
     *     {@link ValidToDate }
     *     
     */
    public ValidToDate getValidToDate() {
        return validToDate;
    }

    /**
     * Sets the value of the validToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidToDate }
     *     
     */
    public void setValidToDate(ValidToDate value) {
        this.validToDate = value;
    }

    /**
     * Gets the value of the userPrivilegeFee property.
     * 
     * @return
     *     possible object is
     *     {@link UserPrivilegeFee }
     *     
     */
    public UserPrivilegeFee getUserPrivilegeFee() {
        return userPrivilegeFee;
    }

    /**
     * Sets the value of the userPrivilegeFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPrivilegeFee }
     *     
     */
    public void setUserPrivilegeFee(UserPrivilegeFee value) {
        this.userPrivilegeFee = value;
    }

    /**
     * Gets the value of the userPrivilegeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link UserPrivilegeStatus }
     *     
     */
    public UserPrivilegeStatus getUserPrivilegeStatus() {
        return userPrivilegeStatus;
    }

    /**
     * Sets the value of the userPrivilegeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPrivilegeStatus }
     *     
     */
    public void setUserPrivilegeStatus(UserPrivilegeStatus value) {
        this.userPrivilegeStatus = value;
    }

    /**
     * Gets the value of the userPrivilegeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link UserPrivilegeDescription }
     *     
     */
    public UserPrivilegeDescription getUserPrivilegeDescription() {
        return userPrivilegeDescription;
    }

    /**
     * Sets the value of the userPrivilegeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPrivilegeDescription }
     *     
     */
    public void setUserPrivilegeDescription(UserPrivilegeDescription value) {
        this.userPrivilegeDescription = value;
    }

}
