//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "noticeType",
    "noticeContent",
    "noticeItemOrUserFiscalAccountOrUserPrivilege"
})
@XmlRootElement(name = "UserNoticeDetails")
public class UserNoticeDetails {

    @XmlElement(name = "NoticeType", required = true)
    protected NoticeType noticeType;
    @XmlElement(name = "NoticeContent")
    protected NoticeContent noticeContent;
    @XmlElements({
        @XmlElement(name = "NoticeItem", required = true, type = NoticeItem.class),
        @XmlElement(name = "UserFiscalAccount", required = true, type = UserFiscalAccount.class),
        @XmlElement(name = "UserPrivilege", required = true, type = UserPrivilege.class)
    })
    protected List<Object> noticeItemOrUserFiscalAccountOrUserPrivilege;

    /**
     * Gets the value of the noticeType property.
     * 
     * @return
     *     possible object is
     *     {@link NoticeType }
     *     
     */
    public NoticeType getNoticeType() {
        return noticeType;
    }

    /**
     * Sets the value of the noticeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoticeType }
     *     
     */
    public void setNoticeType(NoticeType value) {
        this.noticeType = value;
    }

    /**
     * Gets the value of the noticeContent property.
     * 
     * @return
     *     possible object is
     *     {@link NoticeContent }
     *     
     */
    public NoticeContent getNoticeContent() {
        return noticeContent;
    }

    /**
     * Sets the value of the noticeContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoticeContent }
     *     
     */
    public void setNoticeContent(NoticeContent value) {
        this.noticeContent = value;
    }

    /**
     * Gets the value of the noticeItemOrUserFiscalAccountOrUserPrivilege property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noticeItemOrUserFiscalAccountOrUserPrivilege property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoticeItemOrUserFiscalAccountOrUserPrivilege().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoticeItem }
     * {@link UserFiscalAccount }
     * {@link UserPrivilege }
     * 
     * 
     */
    public List<Object> getNoticeItemOrUserFiscalAccountOrUserPrivilege() {
        if (noticeItemOrUserFiscalAccountOrUserPrivilege == null) {
            noticeItemOrUserFiscalAccountOrUserPrivilege = new ArrayList<Object>();
        }
        return this.noticeItemOrUserFiscalAccountOrUserPrivilege;
    }

}
