//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 10:19:21 AM BST 
//


package org.olf.ncip.v1schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "visibleItemIdentifierType",
    "visibleItemIdentifier"
})
@XmlRootElement(name = "VisibleItemId")
public class VisibleItemId {

    @XmlElement(name = "VisibleItemIdentifierType", required = true)
    protected VisibleItemIdentifierType visibleItemIdentifierType;
    @XmlElement(name = "VisibleItemIdentifier", required = true)
    protected VisibleItemIdentifier visibleItemIdentifier;

    /**
     * Gets the value of the visibleItemIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link VisibleItemIdentifierType }
     *     
     */
    public VisibleItemIdentifierType getVisibleItemIdentifierType() {
        return visibleItemIdentifierType;
    }

    /**
     * Sets the value of the visibleItemIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibleItemIdentifierType }
     *     
     */
    public void setVisibleItemIdentifierType(VisibleItemIdentifierType value) {
        this.visibleItemIdentifierType = value;
    }

    /**
     * Gets the value of the visibleItemIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link VisibleItemIdentifier }
     *     
     */
    public VisibleItemIdentifier getVisibleItemIdentifier() {
        return visibleItemIdentifier;
    }

    /**
     * Sets the value of the visibleItemIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibleItemIdentifier }
     *     
     */
    public void setVisibleItemIdentifier(VisibleItemIdentifier value) {
        this.visibleItemIdentifier = value;
    }

}
